---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: routinator

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - service.yml

images:
  - name: docker.io/nlnetlabs/routinator
    newTag: v0.15.2@sha256:bc57d6e973c3f34fec03ef6fec09e17e405f56f084bf2252a8d54bd2ff3ca597
