---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: routinator

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - service.yml

images:
  - name: docker.io/nlnetlabs/routinator
    newTag: v0.15.1@sha256:c7c48cd27bf2076cfe85d743b96669db275a68f907318c085d48c6ddbfde0fbc
