---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-appservices
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        hookshot.yaml: |
          id: matrix-hookshot
          url: http://hookshot:9993
          hs_token: "{{ .hookshot_hs_token }}"
          as_token: "{{ .hookshot_as_token }}"
          rate_limited: false
          sender_localpart: hookshot
          namespaces:
            users:
              - regex: '^@_gitlab_.*:lama\-corp\.space$'
                exclusive: true
              - regex: '^@_webhooks_.*:lama\-corp\.space$'
                exclusive: true
            rooms: []
            aliases:
              - regex: '^#github_.+:lama\-corp\.space'
                exclusive: true
        mautrix-slack.yaml: |
          id: slack
          url: http://mautrix-slack:9993
          hs_token: "{{ .mautrix_slack_hs_token }}"
          as_token: "{{ .mautrix_slack_as_token }}"
          rate_limited: false
          sender_localpart: _bot_slackbot
          namespaces:
            users:
              - regex: '^@slack_[a-z-A-Z0-9\-]+:lama\-corp\.space$'
                exclusive: true
              - regex: '^@slackbot:lama\-corp\.space$'
                exclusive: true
  dataFrom:
    - extract:
        key: /services-matrix/appservices/hookshot
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hookshot_$1"
    - extract:
        key: /services-matrix/appservices/mautrix-slack
      rewrite:
        - regexp:
            source: "(.*)"
            target: "mautrix_slack_$1"
