---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: matrix

resources:
  - appservices.yml
  - network-policy.yml
  - secrets.yml

  - element
  - hookshot
  - mautrix-slack
  - synapse
  - synapse-admin
  - synapse-auto-compressor

images:
  - name: ghcr.io/matrix-org/rust-synapse-compress-state
    newTag: v0.1.4@sha256:b04d1886ec684e94a635a84a8ee705edf2a74f008dcf5b5c0541bba287cde09d
  - name: ghcr.io/etkecc/synapse-admin
    newTag: v0.10.3-etke35@sha256:b7a3848244d9908ff215fad6a01f63dbb7a61ffecf9d7f9fd904d60266372e6d
  - name: docker.io/halfshot/matrix-hookshot
    newTag: 7.3.2@sha256:44283e5131a1a5818bbbf6d9d1e07dccdc29ac5bb6002fcf159af6ac09cf8085
  - name: dock.mau.dev/mautrix/slack
    newTag: v0.2602.0@sha256:042da5f2c9b8be5b72ac6c49ed2b19599bfe4b005cd517cd805877fa48057b26
