# This is an ugly workaround for
# https://github.com/cert-manager/cert-manager/issues/7473
# Until then we'll generate wildcard certificates where needed
# and hopefully, switch to 6-days certificates ASAP
# https://github.com/cert-manager/cert-manager/issues/7695
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-authentik-rs-rsa
spec:
  secretName: eg-http-public-authentik-rs-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "authentik.rs"
    - "*.authentik.rs"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-as212024-net-rsa
spec:
  secretName: eg-http-public-as212024-net-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "as212024.net"
    - "*.as212024.net"
    - "*.k3s.fsn.as212024.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-as212024-net-ecdsa
spec:
  secretName: eg-http-public-as212024-net-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "as212024.net"
    - "*.as212024.net"
    - "*.k3s.fsn.as212024.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-devou-ps-rsa
spec:
  secretName: eg-http-public-devou-ps-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "devou.ps"
    - "*.devou.ps"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-devou-ps-ecdsa
spec:
  secretName: eg-http-public-devou-ps-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "devou.ps"
    - "*.devou.ps"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-doyouhavegoodbackups-com-rsa
spec:
  secretName: eg-http-public-doyouhavegoodbackups-com-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "doyouhavegoodbackups.com"
    - "*.doyouhavegoodbackups.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-doyouhavegoodbackups-com-ecdsa
spec:
  secretName: eg-http-public-doyouhavegoodbackups-com-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "doyouhavegoodbackups.com"
    - "*.doyouhavegoodbackups.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-lama-corp-space-rsa
spec:
  secretName: eg-http-public-lama-corp-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
    - "*.s3.lama-corp.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-lama-corp-space-ecdsa
spec:
  secretName: eg-http-public-lama-corp-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
    - "*.s3.lama-corp.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-lama-tel-rsa
spec:
  secretName: eg-http-public-lama-tel-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama.tel"
    - "*.lama.tel"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-lama-tel-ecdsa
spec:
  secretName: eg-http-public-lama-tel-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama.tel"
    - "*.lama.tel"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-marcerisson-space-rsa
spec:
  secretName: eg-http-public-marcerisson-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "marcerisson.space"
    - "*.marcerisson.space"
    - "*.acdc.marcerisson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-marcerisson-space-ecdsa
spec:
  secretName: eg-http-public-marcerisson-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "marcerisson.space"
    - "*.marcerisson.space"
    - "*.acdc.marcerisson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-risson-me-rsa
spec:
  secretName: eg-http-public-risson-me-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.me"
    - "*.risson.me"
    - "*.acdc.risson.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-risson-me-ecdsa
spec:
  secretName: eg-http-public-risson-me-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.me"
    - "*.risson.me"
    - "*.acdc.risson.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-risson-space-rsa
spec:
  secretName: eg-http-public-risson-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.space"
    - "*.risson.space"
    - "*.acdc.risson.space"
    - "*.home.risson.space"
    - "*.workshop.risson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-risson-space-ecdsa
spec:
  secretName: eg-http-public-risson-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.space"
    - "*.risson.space"
    - "*.acdc.risson.space"
    - "*.home.risson.space"
    - "*.workshop.risson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-rplace-space-rsa
spec:
  secretName: eg-http-public-rplace-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "rplace.space"
    - "*.rplace.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-rplace-space-ecdsa
spec:
  secretName: eg-http-public-rplace-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "rplace.space"
    - "*.rplace.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-cats-acdc-epita-fr-rsa
spec:
  secretName: eg-http-public-cats-acdc-epita-fr-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "cats.acdc.epita.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-cats-acdc-epita-fr-ecdsa
spec:
  secretName: eg-http-public-cats-acdc-epita-fr-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "cats.acdc.epita.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-oup-si-rsa
spec:
  secretName: eg-http-public-oup-si-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "oup.si"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-oup-si-ecdsa
spec:
  secretName: eg-http-public-oup-si-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "oup.si"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-status-prologin-org-rsa
spec:
  secretName: eg-http-public-status-prologin-org-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "status.prologin.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eg-http-public-status-prologin-org-ecdsa
spec:
  secretName: eg-http-public-status-prologin-org-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "status.prologin.org"
