# This is an ugly workaround for
# https://github.com/cert-manager/cert-manager/issues/7473
# Until then we'll generate wildcard certificates where needed
# and hopefully, switch to 6-days certificates ASAP
# https://github.com/cert-manager/cert-manager/issues/7695
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-corp-space-rsa
spec:
  secretName: lama-corp-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-corp-space-ecdsa
spec:
  secretName: lama-corp-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
