# This is an ugly workaround for
# https://github.com/cert-manager/cert-manager/issues/7473
# Until then we'll generate wildcard certificates where needed
# and hopefully, switch to 6-days certificates ASAP
# https://github.com/cert-manager/cert-manager/issues/7695
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: as212024-net-rsa
spec:
  secretName: as212024-net-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "as212024.net"
    - "*.as212024.net"
    - "*.k3s.fsn.as212024.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: as212024-net-ecdsa
spec:
  secretName: as212024-net-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "as212024.net"
    - "*.as212024.net"
    - "*.k3s.fsn.as212024.net"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-rs-rsa
spec:
  secretName: authentik-rs-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "authentik.rs"
    - "*.authentik.rs"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-rs-ecdsa
spec:
  secretName: authentik-rs-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "authentik.rs"
    - "*.authentik.rs"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devou-ps-rsa
spec:
  secretName: devou-ps-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "devou.ps"
    - "*.devou.ps"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devou-ps-ecdsa
spec:
  secretName: devou-ps-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "devou.ps"
    - "*.devou.ps"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doyouhavegoodbackups-com-rsa
spec:
  secretName: doyouhavegoodbackups-com-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "doyouhavegoodbackups.com"
    - "*.doyouhavegoodbackups.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: doyouhavegoodbackups-com-ecdsa
spec:
  secretName: doyouhavegoodbackups-com-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "doyouhavegoodbackups.com"
    - "*.doyouhavegoodbackups.com"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-corp-space-rsa
spec:
  secretName: lama-corp-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-corp-space-ecdsa
spec:
  secretName: lama-corp-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama-corp.space"
    - "*.lama-corp.space"
    - "*.matrix.lama-corp.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-tel-rsa
spec:
  secretName: lama-tel-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama.tel"
    - "*.lama.tel"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lama-tel-ecdsa
spec:
  secretName: lama-tel-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "lama.tel"
    - "*.lama.tel"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marcerisson-space-rsa
spec:
  secretName: marcerisson-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "marcerisson.space"
    - "*.marcerisson.space"
    - "*.acdc.marcerisson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marcerisson-space-ecdsa
spec:
  secretName: marcerisson-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "marcerisson.space"
    - "*.marcerisson.space"
    - "*.acdc.marcerisson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phemma-fr-rsa
spec:
  secretName: phemma-fr-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "phemma.fr"
    - "*.phemma.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: phemma-fr-ecdsa
spec:
  secretName: phemma-fr-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "phemma.fr"
    - "*.phemma.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risson-me-rsa
spec:
  secretName: risson-me-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.me"
    - "*.risson.me"
    - "*.acdc.risson.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risson-me-ecdsa
spec:
  secretName: risson-me-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.me"
    - "*.risson.me"
    - "*.acdc.risson.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risson-space-rsa
spec:
  secretName: risson-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.space"
    - "*.risson.space"
    - "*.acdc.risson.space"
    - "*.home.risson.space"
    - "*.workshop.risson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: risson-space-ecdsa
spec:
  secretName: risson-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "risson.space"
    - "*.risson.space"
    - "*.acdc.risson.space"
    - "*.home.risson.space"
    - "*.workshop.risson.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rplace-space-rsa
spec:
  secretName: rplace-space-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "rplace.space"
    - "*.rplace.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rplace-space-ecdsa
spec:
  secretName: rplace-space-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "rplace.space"
    - "*.rplace.space"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sdlh-eu-rsa
spec:
  secretName: sdlh-eu-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "sdlh.eu"
    - "*.sdlh.eu"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sdlh-eu-ecdsa
spec:
  secretName: sdlh-eu-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns01
  dnsNames:
    - "sdlh.eu"
    - "*.sdlh.eu"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cats-acdc-epita-fr-rsa
spec:
  secretName: cats-acdc-epita-fr-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "cats.acdc.epita.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cats-acdc-epita-fr-ecdsa
spec:
  secretName: cats-acdc-epita-fr-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "cats.acdc.epita.fr"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oup-si-rsa
spec:
  secretName: oup-si-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "oup.si"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oup-si-ecdsa
spec:
  secretName: oup-si-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "oup.si"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-prologin-org-rsa
spec:
  secretName: status-prologin-org-rsa-tls
  privateKey:
    algorithm: RSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "status.prologin.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-prologin-org-ecdsa
spec:
  secretName: status-prologin-org-ecdsa-tls
  privateKey:
    algorithm: ECDSA
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-http01-eg
  dnsNames:
    - "status.prologin.org"
