---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-http-media
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  nodeSelector:
                    k8s.as212024.net/role: media
                  tolerations:
                    - key: k8s.as212024.net/role
                      operator: Equal
                      value: media
                      effect: NoExecute
      envoyService:
        externalTrafficPolicy: Local
      envoyPDB:
        minAvailable: 1
  logging:
    level:
      default: info
  ipFamily: DualStack
