---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg-http-public
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: eg-http-public
    annotations:
      io.cilium/lb-ipam-ips: 148.251.148.235,2001:67c:17fc:130::443
      external-dns.alpha.kubernetes.io/hostname: gw-eg-http-public.k3s.fsn.as212024.net
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: as212024-net-ecdsa-tls
          - name: as212024-net-rsa-tls
          - name: devou-ps-ecdsa-tls
          - name: devou-ps-rsa-tls
          - name: doyouhavegoodbackups-com-ecdsa-tls
          - name: doyouhavegoodbackups-com-rsa-tls
          - name: lama-corp-space-ecdsa-tls
          - name: lama-corp-space-rsa-tls
          - name: lama-tel-ecdsa-tls
          - name: lama-tel-rsa-tls
          - name: marcerisson-space-ecdsa-tls
          - name: marcerisson-space-rsa-tls
          - name: risson-me-ecdsa-tls
          - name: risson-me-rsa-tls
          - name: risson-space-ecdsa-tls
          - name: risson-space-rsa-tls
          - name: rplace-space-ecdsa-tls
          - name: rplace-space-rsa-tls
          - name: cats-acdc-epita-fr-ecdsa-tls
          - name: cats-acdc-epita-fr-rsa-tls
          - name: oup-si-ecdsa-tls
          - name: oup-si-rsa-tls
          - name: status-prologin-org-ecdsa-tls
          - name: status-prologin-org-rsa-tls
