---
kind: Kustomization

resources:
  - ../base

  - backendtrafficpolicy.yml
  - clienttrafficpolicy.yml
  - httproute-http-to-https.yml

  - gateway-eg-http-public.yml
  - gateway-eg-http-media.yml
  - gateway-eg-http-bar.yml
  - envoyproxy-eg-http-public.yml
  - envoyproxy-eg-http-media.yml
  - envoyproxy-eg-http-bar.yml

  - certificates.yml
