---
apiVersion: v1
kind: Service
metadata:
  name: coredns-lb
  annotations:
    io.cilium/lb-ipam-ips: 209.112.97.160,2001:67c:17fc:130::53
    external-dns.kubernetes.io/hostname: ns.dns.c.k3s.fsn.as212024.net
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
      targetPort: 53
    - name: tcp-53
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    k8s-app: kube-dns
