---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: bird

resources:
  - daemonset.yml

configMapGenerator:
  - name: bird-config
    files:
      - config/start.sh
      - config/bird.conf

images:
  - name: ghcr.io/akafeng/bird
    newTag: 3.2@sha256:5f959555445306914da3cff316be8a15c57a5fbd250fb102d3ebdf7391021253
