---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-gateway-api
  labels:
    app: core-gateway-api
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: core-gateway-api-{{ .name }}
      labels:
        app: core-gateway-api
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: kube-system
      source:
        repoURL: https://github.com/LamaCorp/infrastructure.git
        targetRevision: HEAD
        path: k8s/core/gateway-api/app
