---
bird_router_id: 209.112.97.242

bird_bgp_preferred_source:
  v4: 209.112.97.242
  v6: 2001:67c:17fc:ffff::2

bird_static_routes:
  v4:
    - 209.112.97.123/32 unreachable # ntp0.as212024.net
    - 209.112.97.235/32 unreachable # nat-svc
    - 209.112.97.236/32 unreachable # nat-pb
    - 209.112.97.237/32 unreachable # nat-music-iot-cctv
    - 209.112.97.238/32 unreachable # nat-pharma
  v6:
    - 2001:67c:17fc::123/128 unreachable # ntp0.as212024.net

bird_bgp_sessions:
  cores:
    defaults:
      local:
        v4: 209.112.97.242
        v6: 2001:67c:17fc:ffff::2
      med_metric: true
    sessions:
      # - description: FSN
      #   alias: fsn
      #   asn: 212024
      #   remote:
      #     v4: 209.112.97.241
      #     v6: 2001:67c:17fc:ffff::1
      - description: PVL
        alias: pvl
        asn: 212024
        remote:
          v4: 209.112.97.243
          v6: 2001:67c:17fc:ffff::3
      - description: FRA
        alias: fra
        asn: 212024
        remote:
          v4: 209.112.97.244
          v6: 2001:67c:17fc:ffff::4
      # - description: FSN4
      #   alias: fsn4
      #   asn: 212024
      #   interface: core-fsn-4
      #   local:
      #     v4: 169.254.4.1
      #     v6: fe80::4:1
      #   remote:
      #     v4: 169.254.4.0
      #     v6: fe80::4:0
      # - description: FSN6
      #   alias: fsn6
      #   asn: 212024
      #   interface: core-fsn-6
      #   local:
      #     v4: 169.254.6.1
      #     v6: fe80::6:1
      #   remote:
      #     v4: 169.254.6.0
      #     v6: fe80::6:0
      # - description: PVL4
      #   alias: pvl4
      #   asn: 212024
      #   interface: core-pvl-4
      #   local:
      #     v4: 169.254.4.6
      #     v6: fe80::4:6
      #   remote:
      #     v4: 169.254.4.7
      #     v6: fe80::4:7
      # - description: PVL6
      #   alias: pvl6
      #   asn: 212024
      #   interface: core-pvl-6
      #   local:
      #     v4: 169.254.6.6
      #     v6: fe80::6:6
      #   remote:
      #     v4: 169.254.6.7
      #     v6: fe80::6:7
      # - description: FRA4
      #   alias: fra4
      #   asn: 212024
      #   interface: core-fra-4
      #   local:
      #     v4: 169.254.4.8
      #     v6: fe80::4:8
      #   remote:
      #     v4: 169.254.4.9
      #     v6: fe80::4:9
      # - description: FRA6
      #   alias: fra6
      #   asn: 212024
      #   interface: core-fra-6
      #   local:
      #     v4: 169.254.6.8
      #     v6: fe80::6:8
      #   remote:
      #     v4: 169.254.6.9
      #     v6: fe80::6:9

bird_ospf_sessions:
  - alias: ospf
    export_static_routes: true
    areas:
      0.0.0.0:
        stubnets:
          v6:
            - prefix: 2a01:cb10::/30
              hidden: true
              summary: true
        interfaces:
          zt-lama:
            cost: 50
          # core-fsn-4:
          #   type: ptp
          #   cost: 100
          # core-fsn-6:
          #   type: ptp
          #   cost: 100
          # core-pvl-4:
          #   type: ptp
          #   cost: 100
          # core-pvl-6:
          #   type: ptp
          #   cost: 100
          # core-fra-4:
          #   type: ptp
          #   cost: 100
          # core-fra-6:
          #   type: ptp
          #   cost: 100
          lan-srv-2:
            cost: 1
          lan-mgmt-0:
            stub: true
          lan-pb-4:
            stub: true
          lan-svc-7:
            stub: true
          cl-home-2050:
            stub: true
          cl-iot-2092:
            stub: true
          cl-music-2093:
            stub: true
          cl-cctv-2094:
            stub: true
          cl-pharma-2099:
            stub: true

bird_radv_sessions:
  - alias: radv6
    interfaces:
      lan-mgmt-0:
        mtu: 9000
      cl-iot-2092:
        mtu: 1500
      cl-cctv-2094:
        mtu: 1500
    rdnss:
      - ns:
          - 2001:67c:17fc:ffff::2
