---
bird_router_id: 209.112.97.242

bird_bgp_preferred_source:
  v4: 209.112.97.242
  v6: 2001:67c:17fc:ffff::2

bird_static_routes:
  v4:
    - 209.112.97.123/32 unreachable # ntp0.as212024.net
    - 209.112.97.235/32 unreachable # nat-svc
    - 209.112.97.236/32 unreachable # nat-pb
    - 209.112.97.237/32 unreachable # nat-music-iot-cctv
    - 209.112.97.238/32 unreachable # nat-pharma
  v6:
    - 2001:67c:17fc::123/128 unreachable # ntp0.as212024.net

bird_bgp_sessions:
  cores:
    defaults:
      local:
        v4: 209.112.97.242
        v6: 2001:67c:17fc:ffff::2
      med_metric: true
    sessions:
      - description: FSN
        alias: fsn
        asn: 212024
        remote:
          v4: 209.112.97.241
          v6: 2001:67c:17fc:ffff::1
      - description: PVL
        alias: pvl
        asn: 212024
        remote:
          v4: 209.112.97.243
          v6: 2001:67c:17fc:ffff::3
      - description: FRA
        alias: fra
        asn: 212024
        remote:
          v4: 209.112.97.244
          v6: 2001:67c:17fc:ffff::4

bird_ospf_sessions:
  - alias: ospf
    export_static_routes: true
    areas:
      0.0.0.0:
        stubnets:
          v6:
            - prefix: 2a01:cb10::/30
              hidden: true
              summary: true
        interfaces:
          zt-lama:
            cost: 50
          lan-srv-2:
            cost: 1
          lan-mgmt-0:
            stub: true
          lan-pb-4:
            stub: true
          lan-svc-7:
            stub: true
          cl-home-2050:
            stub: true
          cl-iot-2092:
            stub: true
          cl-music-2093:
            stub: true
          cl-cctv-2094:
            stub: true
          cl-pharma-2099:
            stub: true

bird_radv_sessions:
  - alias: radv6
    interfaces:
      lan-mgmt-0:
        mtu: 9000
      cl-iot-2092:
        mtu: 1500
      cl-cctv-2094:
        mtu: 1500
    rdnss:
      - ns:
          - 2001:67c:17fc:ffff::2
