---
kea_ctrl_agent_enable: true
kea_dhcp4_enable: true
kea_dhcp6_enable: false
kea_dhcp_ddns_enable: false

kea_ctrl_agent_config:
  Control-agent:
    http-port: 8001
kea_dhcp4_config:
  Dhcp4:
    interfaces-config:
      interfaces:
        - lan-mgmt-0
        - cl-cctv-2094
        - cl-home-2050
        - cl-iot-2092
        - cl-music-2093
        - cl-pharma-2099
      dhcp-socket-type: raw
    lease-database:
      persist: true
      lfc-interval: 0
    calculate-tee-times: true
    valid-lifetime: 86400
    next-server: 172.28.2.254
    option-data:
      - name: no-pxedhcp
        code: 176
        space: ipxe
        data: "1"
        always-send: true
    client-classes:
      - name: ipxe_efi_x86
        test: "option[client-system].hex == 0x0006"
        boot-file-name: ipxe.efi
      - name: ipxe_efi_x64
        test: "option[client-system].hex == 0x0007"
        boot-file-name: ipxe.efi
      - name: ipxe_efi_x64_x86
        test: "option[client-system].hex == 0x0009"
        boot-file-name: ipxe.efi
      - name: ipxe_legacy_x64
        test: "not option[client-system].hex == 0x0006 and not option[client-system].hex == 0x0007 and not option[client-system].hex == 0x0009"
        boot-file-name: undionly.kpxe
    option-def:
      - name: no-pxedhcp
        code: 176
        type: uint8
        array: false
        record-types: ""
        space: ipxe
        encapsulate: ""
      - name: https
        code: 20
        type: uint8
        array: false
        record-types: ""
        space: ipxe
        encapsulate: ""
    subnet4:
      - id: 1
        subnet: 172.28.2.224/27
        valid-lifetime: 600
        pools:
          - pool: 172.28.2.226 - 172.28.2.229
        option-data:
          - name: routers
            data: 172.28.2.254
          - name: domain-name-servers
            data: 172.28.2.254
          - name: domain-name
            data: bar.as212024.net
          - name: ntp-servers
            data: 172.28.2.254
        reservations:
          - hw-address: 84:78:48:b6:f1:60
            ip-address: 172.28.2.239
            hostname: udb-bureau
          - hw-address: e4:38:83:e7:22:d8
            ip-address: 172.28.2.240
            hostname: wifi-1
          - hw-address: e4:38:83:e7:21:38
            ip-address: 172.28.2.241
            hostname: wifi-0
          - hw-address: 28:70:4e:d0:eb:de
            ip-address: 172.28.2.242
            hostname: wifi-bureau
          - hw-address: 28:70:4e:d2:d0:64
            ip-address: 172.28.2.248
            hostname: sw-bureau
          - hw-address: a0:a0:01:a1:06:10
            ip-address: 172.28.2.249
            hostname: sw-marc
          - hw-address: a8:52:d4:93:0f:4d
            ip-address: 172.28.2.250
            hostname: sw-1
          - hw-address: a8:52:d4:94:15:9c
            ip-address: 172.28.2.251
            hostname: sw-0
          - hw-address: 1c:6a:1b:67:3d:71
            ip-address: 172.28.2.252
            hostname: sw-piscine
      - id: 2050
        subnet: 172.29.2.0/24
        pools:
          - pool: 172.29.2.100 - 172.29.2.199
        option-data:
          - name: classless-static-route
            data: 209.112.97.0/24 - 172.29.2.254, 172.28.0.0/15 - 172.29.2.254, 0.0.0.0/0 - 172.29.2.1
          - name: routers
            data: 172.29.2.1
          - name: domain-name-servers
            data: 172.29.2.254
          - name: domain-name
            data: client.bar.risson.net
          - name: ntp-servers
            data: 172.29.2.254
        reservations:
          - hw-address: d8:3a:dd:11:23:8b
            ip-address: 172.29.2.210
            hostname: v-core-3
          - hw-address: 00:09:82:17:1c:c0
            ip-address: 172.29.2.220
            hostname: loewe-tv
          - hw-address: 08:df:1f:08:49:34
            ip-address: 172.29.2.221
            hostname: bose-office
          - hw-address: 48:d6:d5:27:2b:b4
            ip-address: 172.29.2.222
            hostname: chromecast-tv
          - hw-address: 88:51:fb:1b:21:f4
            ip-address: 172.29.2.230
            hostname: hp-office
          - hw-address: b8:27:eb:23:aa:a8
            ip-address: 172.29.2.51
            hostname: arrosoir
      - id: 2092
        subnet: 172.29.192.0/24
        pools:
          - pool: 172.29.192.200 - 172.29.192.220
        option-data:
          - name: routers
            data: 172.29.192.254
          - name: domain-name-servers
            data: 172.29.192.254
          - name: domain-name
            data: iot.bar.risson.net
          - name: ntp-servers
            data: 172.29.192.254
        reservations:
          - hw-address: e4:65:b8:d9:0d:9f
            ip-address: 172.29.192.10
            hostname: slzb-06p10-0
          - hw-address: b8:74:24:2e:c3:3f
            ip-address: 172.29.192.64
            hostname: viessmann-6221
          - hw-address: c0:e4:34:41:5e:46
            ip-address: 172.29.192.65
            hostname: roomba-1
          - hw-address: 54:ef:44:56:11:0a
            ip-address: 172.29.192.66
            hostname: presense-sensor-chambre-marc
          - hw-address: ac:48:2d:13:f2:6e
            ip-address: 172.29.192.67
            hostname: apsystems-ecu-c
          - hw-address: c8:c9:a3:8f:d9:ec
            ip-address: 172.29.192.68
            hostname: everbluemeters
          - hw-address: 24:d7:eb:e7:52:c3
            ip-address: 172.29.192.69
            hostname: iotawatt-1
      - id: 2093
        subnet: 172.29.193.0/24
        pools:
          - pool: 172.29.193.200 - 172.29.193.220
        option-data:
          - name: routers
            data: 172.29.193.254
          - name: domain-name-servers
            data: 172.29.193.254
          - name: domain-name
            data: music.bar.risson.net
          - name: ntp-servers
            data: 172.29.193.254
        reservations: []
      - id: 2094
        subnet: 172.29.194.0/24
        pools:
          - pool: 172.29.194.200 - 172.29.194.220
        option-data:
          - name: routers
            data: 172.29.194.254
          - name: domain-name-servers
            data: 172.29.194.254
          - name: domain-name
            data: cctv.bar.risson.net
          - name: ntp-servers
            data: 172.29.194.254
        reservations:
          - hw-address: ec:71:db:a9:1f:b7
            ip-address: 172.29.194.10
            hostname: avant
          - hw-address: ec:71:db:4c:cd:69
            ip-address: 172.29.194.11
            hostname: entree
          - hw-address: ec:71:db:65:f3:3c
            ip-address: 172.29.194.12
            hostname: cote
          - hw-address: ec:71:db:bd:82:ab
            ip-address: 172.29.194.13
            hostname: arriere
          - hw-address: ec:71:db:34:00:ea
            ip-address: 172.29.194.14
            hostname: terrasse-bas
      - id: 2099
        subnet: 192.168.0.0/24
        pools:
          - pool: 192.168.0.100 - 192.168.0.199
        option-data:
          - name: routers
            data: 192.168.0.254
          - name: domain-name-servers
            data: 192.168.0.254
          - name: domain-name
            data: pharma.bar.risson.net
          - name: ntp-servers
            data: 192.168.0.254
        reservations: []
