---
network_nameservers:
  - ::1
  - 127.0.0.1

netplan_configuration:
  network:
    version: 2
    ethernets:
      enp1s0f0: {}
      enp1s0f1: {}
    bonds:
      bond0:
        interfaces:
          - enp1s0f0
          - enp1s0f1
        parameters:
          mode: 802.3ad
          lacp-rate: fast
          transmit-hash-policy: layer3+4
        mtu: 9000
        accept-ra: false
        addresses:
          - 172.28.2.254/27
          - 2001:67c:17fc:201::1/64
        routes:
          - to: 209.112.97.235/32 # nat-svc
            via: 0.0.0.0
            type: unreachable
    vlans:
      bar-srv:
        id: 2
        link: bond0
        mtu: 9000
        accept-ra: false
        addresses:
          - 172.28.2.30/27
          - 2001:67c:17fc:202::1/64
      bar-pb:
        id: 4
        link: bond0
        mtu: 9000
        accept-ra: false
        addresses:
          - 172.28.2.94/27
          - 2001:67c:17fc:204::1/64
        routes:
          - to: 209.112.97.123/32 # ntp0.as2120240.net
            via: 172.28.2.65 # ntp-1.bar.as212024.net
          - to: 2001:67c:17fc::123/128 # ntp0.as212024.net
            via: 2001:67c:17fc:204::123 # ntp-1.bar.as212024.net
          - to: 209.112.97.236/32 # nat-pb
            via: 0.0.0.0
            type: unreachable
      bar-svc:
        id: 7
        link: bond0
        mtu: 9000
        accept-ra: false
        addresses:
          - 172.28.2.222/27
          - 2001:67c:17fc:207::1/64
      bar-client:
        id: 2050
        link: bond0
        mtu: 1500
        accept-ra: false
        addresses:
          - 172.29.2.254/24
          - 172.29.2.99/24
        routes:
          - to: 0.0.0.0/0
            via: 172.29.2.1
          - to: 0.0.0.0/0
            via: 172.29.2.1
            table: 101
        routing-policy:
          - from: 192.168.0.0/24
            table: 101
      bar-iot:
        id: 2092
        link: bond0
        mtu: 1500
        accept-ra: false
        addresses:
          - 172.29.192.254/24
          - 2a06:e881:7701:192::1/64
        routes:
          - to: 209.112.97.237/32 # nat-music-iot-cctv
            via: 0.0.0.0
            type: unreachable
      bar-music:
        id: 2093
        link: bond0
        mtu: 9000
        accept-ra: false
        addresses:
          - 172.29.193.254/24
          - 2a06:e881:7701:193::1/64
      bar-cctv:
        id: 2094
        link: bond0
        mtu: 1500
        accept-ra: false
        addresses:
          - 172.29.194.254/24
          - 2a06:e881:7701:194::1/64
      bar-pharma:
        id: 2099
        link: bond0
        mtu: 1500
        accept-ra: false
        addresses:
          - 192.168.0.200/24
        routes:
          - to: 209.112.97.238/32 # nat-pharma
            via: 0.0.0.0
            type: unreachable
