---
systemd_networkd_link:
  # 10GB SFP+
  10-lan-mgmt-0-m0:
    Match:
      MACAddress: a8:b8:e0:07:92:1f
    Link:
      Name: lan-mgmt-0-m0
  10-lan-mgmt-0-m1:
    Match:
      MACAddress: a8:b8:e0:07:92:20
    Link:
      Name: lan-mgmt-0-m1
  # 2.5GB LAN
  10-unused-0:
    Match:
      MACAddress: a8:b8:e0:07:92:21
    Link:
      Name: unused-0
  10-unused-1:
    Match:
      MACAddress: a8:b8:e0:07:92:22
    Link:
      Name: unused-1

systemd_networkd_netdev:
  10-id:
    NetDev:
      Name: id
      Kind: dummy
  # management network
  10-lan-mgmt-0:
    NetDev:
      Name: lan-mgmt-0
      Kind: bond
      MTUBytes: 9000
    Bond:
      Mode: 802.3ad
      LACPTransmitRate: fast
      TransmitHashPolicy: layer3+4
  # core VPN
  15-core-fsn:
    NetDev:
      Name: core-fsn
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51801
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '~/.ansible/tmp/wireguard/nucleus.fsn.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "136.243.102.29:51802"
  15-core-pvl:
    NetDev:
      Name: core-pvl
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51803
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '~/.ansible/tmp/wireguard/edge-1.pvl.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "108.61.208.236:51802"
  15-core-fra:
    NetDev:
      Name: core-fra
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51804
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '~/.ansible/tmp/wireguard/edge-2.fra.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "194.50.92.165:51802"
  # servers, like k8s
  20-lan-srv-2:
    NetDev:
      Name: lan-srv-2
      Kind: vlan
      MTUBytes: 1420
    VLAN:
      Id: 2
  # public benefit, like NTP stratum 1
  20-lan-pb-4:
    NetDev:
      Name: lan-pb-4
      Kind: vlan
      MTUBytes: 1420
    VLAN:
      Id: 4
  # local services, like home-assistant
  20-lan-svc-7:
    NetDev:
      Name: lan-svc-7
      Kind: vlan
      MTUBytes: 1420
    VLAN:
      Id: 7
  # home clients
  30-cl-home-2050:
    NetDev:
      Name: cl-home-2050
      Kind: vlan
      MTUBytes: 1500
    VLAN:
      Id: 2050
  # IoT devices
  30-cl-iot-2092:
    NetDev:
      Name: cl-iot-2092
      Kind: vlan
      MTUBytes: 1500
    VLAN:
      Id: 2092
  # music control and speakers
  30-cl-music-2093:
    NetDev:
      Name: cl-music-2093
      Kind: vlan
      MTUBytes: 9000
    VLAN:
      Id: 2093
  # cameras
  30-cl-cctv-2094:
    NetDev:
      Name: cl-cctv-2094
      Kind: vlan
      MTUBytes: 1500
    VLAN:
      Id: 2094
  # temporary for pharma equipment
  30-cl-pharma-2099:
    NetDev:
      Name: cl-pharma-2099
      Kind: vlan
      MTUBytes: 1500
    VLAN:
      Id: 2099

systemd_networkd_network:
  10-id:
    Match:
      Name: id
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: false
      Address:
        - 209.112.97.242/32
        - 2001:67c:17fc:ffff::2/128
  10-lan-mgmt-0-m:
    Match:
      Name: lan-mgmt-0-m*
    Network:
      LinkLocalAddressing: false
      Bond: lan-mgmt-0
  # management network
  10-lan-mgmt-0:
    Match:
      Name: lan-mgmt-0
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      VLAN:
        - lan-srv-2
        - lan-pb-4
        - lan-svc-7
        - cl-home-2050
        - cl-iot-2092
        - cl-music-2093
        - cl-cctv-2094
        - cl-pharma-2099
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.2.254/27
      DHCPServer: true
      IPv6SendRA: true
    Route:
      - Destination: 209.112.97.235/32 # nat-svc
        Gateway: 0.0.0.0
        Type: unreachable
    DHCPServer:
      PoolOffset: 2
      PoolSize: 3
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 172.28.2.254
      NTP: 172.28.2.254
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: bar.as212024.net
    DHCPServerStaticLease:
      - Hostname: panda
        MACAddress: 00:e0:4c:50:00:65
        Address: 172.28.2.225
      - Hostname: udb-bureau
        MACAddress: 84:78:48:b6:f1:60
        Address: 172.28.2.239
      - Hostname: wifi-1
        MACAddress: e4:38:83:e7:22:d8
        Address: 172.28.2.240
      - Hostname: wifi-0
        MACAddress: e4:38:83:e7:21:38
        Address: 172.28.2.241
      - Hostname: wifi-bureau
        MACAddress: 28:70:4e:d0:eb:de
        Address: 172.28.2.242
      - Hostname: sw-bureau
        MACAddress: 28:70:4e:d2:d0:64
        Address: 172.28.2.248
      - Hostname: sw-marc
        MACAddress: a0:a0:01:a1:06:10
        Address: 172.28.2.249
      - Hostname: sw-1
        MACAddress: a8:52:d4:93:0f:4d
        Address: 172.28.2.250
      - Hostname: sw-0
        MACAddress: a8:52:d4:94:15:9c
        Address: 172.28.2.251
      - Hostname: sw-piscine
        MACAddress: 1c:6a:1b:67:3d:71
        Address: 172.28.2.252
    IPv6SendRA:
      DNS: 2001:67c:17fc:ffff::2
      Domains: bar.as212024.net
    IPv6Prefix:
      - Prefix: 2001:67c:17fc:201::0/64
        Assign: true
        Token: static:::1
  # core VPN
  15-core-fsn:
    Match:
      Name: core-fsn
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: false
      IPv6AcceptRA: false
      Address:
        - 169.254.0.1/31
        - fe80::0:1/127
  15-core-pvl:
    Match:
      Name: core-pvl
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: false
      IPv6AcceptRA: false
      Address:
        - 169.254.0.6/31
        - fe80::0:6/127
  15-core-fra:
    Match:
      Name: core-fra
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: false
      IPv6AcceptRA: false
      Address:
        - 169.254.0.8/31
        - fe80::0:8/127
  # servers, like k8s
  20-lan-srv-2:
    Match:
      Name: lan-srv-2
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.2.30/27
        - 2001:67c:17fc:202::1/64
  # public benefit, like NTP stratum 1
  20-lan-pb-4:
    Match:
      Name: lan-pb-4
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.2.94/27
        - 2001:67c:17fc:204::1/64
    Route:
      - Destination: 209.112.97.123/32 # ntp0.as212024.net
        Gateway: 172.28.2.65 # ntp-1.bar.as212024.net
      - Destination: 2001:67c:17fc::123/128 # ntp0.as212024.net
        Gateway: 2001:67c:17fc:204::123 # ntp-1.bar.as212024.net
      - Destination: 209.112.97.236/32 # nat-pb
        Gateway: 0.0.0.0
        Type: unreachable
  # local services, like home-assistant
  20-lan-svc-7:
    Match:
      Name: lan-svc-7
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.2.222/27
        - 2001:67c:17fc:207::1/64
  # home clients
  30-cl-home-2050:
    Match:
      Name: cl-home-2050
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.2.254/24
        - 172.29.2.99/24 # for pharma NAT
      DHCPServer: true
    Route:
      # Default routes
      - Destination: 0.0.0.0/0
        Gateway: 172.29.2.1
      - Destination: 0.0.0.0/0
        Gateway: 172.29.2.1
        Table: 101
    RoutingPolicyRule:
      # from pharma
      - From: 192.168.0.0/24
        Table: 101
      - To: 136.243.102.29/32
        Table: 101
      # core VPN
      - To: 108.61.208.236/32
        Table: 101
      - To: 2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb/128
        Table: 101
      - To: 194.50.92.165/32
        Table: 101
      - To: 2a09:4c0:303:c232::5ca5/128
        Table: 101
    DHCPServer:
      ServerAddress: 172.29.2.254/24
      PoolOffset: 100
      PoolSize: 100
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 172.29.2.254
      NTP: 172.29.2.254
      Router: 172.29.2.1
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: client.bar.risson.net
      # Extra routes: 209.112.97.0/24 -> 172.29.2.254, 172.28.0.0/15 -> 172.29.2.254, 0.0.0.0/0 -> 172.29.2.1
      SendOption: "121:string:\\x18\\xd1\\x70\\x61\\xac\\x1d\\x02\\xfe\\x0f\\xac\\x1c\\xac\\x1d\\x02\\xfe\\x00\\xac\\x1d\\x02\\x01"
    DHCPServerStaticLease:
      - Hostname: v-core-3
        MACAddress: d8:3a:dd:11:23:8b
        Address: 172.29.2.210
      - Hostname: loewe-tv
        MACAddress: 00:09:82:17:1c:c0
        Address: 172.29.2.220
      - Hostname: bose-office
        MACAddress: 08:df:1f:08:49:34
        Address: 172.29.2.221
      - Hostname: chromecast-tv
        MACAddress: 48:d6:d5:27:2b:b4
        Address: 172.29.2.222
      - Hostname: hp-office
        MACAddress: 88:51:fb:1b:21:f4
        Address: 172.29.2.230
      - Hostname: arrosoir
        MACAddress: b8:27:eb:23:aa:a8
        Address: 172.29.2.51
  # IoT devices
  30-cl-iot-2092:
    Match:
      Name: cl-iot-2092
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.192.254/24
        - 2a06:e881:7701:192::1/64
      DHCPServer: true
      IPv6SendRA: true
    Route:
      - Destination: 209.112.97.237/32 # nat-music-iot-cctv
        Gateway: 0.0.0.0
        Type: unreachable
    DHCPServer:
      PoolOffset: 200
      PoolSize: 20
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 172.29.192.254
      NTP: 172.29.192.254
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: iot.bar.risson.net
    DHCPServerStaticLease:
      - Hostname: slzb-06p10-0
        MACAddress: e4:65:b8:d9:0d:9f
        Address: 172.29.192.10
      - Hostname: viessmann-6221
        MACAddress: b8:74:24:2e:c3:3f
        Address: 172.29.192.64
      - Hostname: roomba-1
        MACAddress: c0:e4:34:41:5e:46
        Address: 172.29.192.65
      - Hostname: presense-sensor-chambre-marc
        MACAddress: 54:ef:44:56:11:0a
        Address: 172.29.192.66
      - Hostname: apsystems-ecu-c
        MACAddress: ac:48:2d:13:f2:6e
        Address: 172.29.192.67
      - Hostname: everbluemeters
        MACAddress: c8:c9:a3:8f:d9:ec
        Address: 172.29.192.68
      - Hostname: iotawatt-1
        MACAddress: 24:d7:eb:e7:52:c3
        Address: 172.29.192.69
    IPv6SendRA:
      DNS: 2001:67c:17fc:ffff::2
      Domains: iot.bar.risson.net
    IPv6Prefix:
      - Prefix: 2a06:e881:7701:192::/64
        Assign: true
        Token: static:::1
  # music control and speakers
  30-cl-music-2093:
    Match:
      Name: cl-music-2093
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.193.254/24
        - 2a06:e881:7701:193::1/64
      DHCPServer: true
    DHCPServer:
      PoolOffset: 200
      PoolSize: 20
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 172.29.193.254
      NTP: 172.29.193.254
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: music.bar.risson.net
  # cameras
  30-cl-cctv-2094:
    Match:
      Name: cl-cctv-2094
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.194.254/24
        - 2a06:e881:7701:194::1/64
      DHCPServer: true
    DHCPServer:
      PoolOffset: 200
      PoolSize: 20
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 172.29.194.254
      NTP: 172.29.194.254
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: cctv.bar.risson.net
    DHCPServerStaticLease:
      - Hostname: avant
        MACAddress: ec:71:db:a9:1f:b7
        Address: 172.29.194.10
      - Hostname: entree
        MACAddress: ec:71:db:4c:cd:69
        Address: 172.29.194.11
      - Hostname: cote
        MACAddress: ec:71:db:65:f3:3c
        Address: 172.29.194.12
      - Hostname: arriere
        MACAddress: ec:71:db:bd:82:ab
        Address: 172.29.194.13
      - Hostname: terrasse-bas
        MACAddress: ec:71:db:34:00:ea
        Address: 172.29.194.14
  # temporary for pharma equipment
  30-cl-pharma-2099:
    Match:
      Name: cl-pharma-2099
    Link:
      RequiredForOnline: true
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 192.168.0.200/24
      DHCPServer: true
    Route:
      - Destination: 209.112.97.238/32 # nat-pharma
        Gateway: 0.0.0.0
        Type: unreachable
    DHCPServer:
      PoolOffset: 100
      PoolSize: 100
      DefaultLeaseTimeSec: 43200
      MaxLeaseTimeSec: 86400
      DNS: 192.168.0.200
      NTP: 192.168.0.200
      EmitSIP: false
      EmitPOP3: false
      EmitSMTP: false
      EmitLPR: false
      EmitDomain: true
      Domain: pharma.bar.risson.net
