---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-vault
  labels:
    app: infra-vault
spec:
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: infra-vault
  sources:
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      ref: infrastructure
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.34.0
      chart: vault
      helm:
        releaseName: vault
        valueFiles:
          - $infrastructure/k8s/infra/vault/values.yml
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      path: k8s/infra/vault/extra
