---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-vault
  labels:
    app: infra-vault
spec:
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: infra-vault
  sources:
    - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
      targetRevision: HEAD
      path: k8s/infra/vault/extra
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.32.0
      chart: vault
      helm:
        releaseName: vault
        values: |
          global:
            tlsDisable: true
            serverTelemetry:
              prometheusOperator: true

          server:
            enabled: true

            standalone:
              enabled: true
              config: |
                disable_mlock = true
                ui = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  telemetry {
                    unauthenticated_metrics_access = "true"
                  }
                }
                storage "file" {
                  path = "/vault/data"
                }

                telemetry {
                  prometheus_retention_time = "30s"
                  disable_hostname = true
                }

            readinessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
            livenessProble:
              enabled: true
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
              initialDelaySeconds: 60

            dataStorage:
              enabled: true

          serverTelemetry:
            serviceMonitor:
              enabled: true
            prometheusRules:
              enabled: true
              rules:
                - alert: VaultSealed
                  annotations:
                    summary: Vault is sealed.
                  expr: vault_core_unsealed == 0
                  for: 5m
                  labels:
                    severity: critical
                - alert: VaultHighResponseTime
                  annotations:
                    summary: The response time of Vault is over 500ms on average over the last 5 minutes.
                  expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
                  for: 5m
                  labels:
                    severity: warning
                - alert: VaultHighResponseTime
                  annotations:
                    summary: The response time of Vault is over 1s on average over the last 5 minutes.
                  expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
                  for: 5m
                  labels:
                    severity: critical

          injector:
            enabled: false
