---
global:
  tlsDisable: true
  serverTelemetry:
    prometheusOperator: true

server:
  enabled: true

  image:
    registry: ""
    repository: quay.io/openbao/openbao-ubi
    tag: 2.6.2

  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        telemetry {
          unauthenticated_metrics_access = "true"
        }
      }
      storage "file" {
        path = "/openbao/data"
      }

      telemetry {
        prometheus_retention_time = "30s"
        disable_hostname = true
      }

      plugin_auto_download = true
      plugin_auto_register = true

      plugin "database" "mongodb" {
        image = "ghcr.io/openbao/openbao-plugin-database-mongodb"
        version = "v0.0.1"
        binary_name = "openbao-plugin-database-mongodb"
        sha256sum = "4768e4e573c261e44a004adc9a3564c43824aa0be4cb98c871fd46a7bea25d0c"
      }

  # readinessProbe:
  #   enabled: true
  #   path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  # livenessProble:
  #   enabled: true
  #   path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  #   initialDelaySeconds: 60

  dataStorage:
    enabled: true

serverTelemetry:
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true
    rules:
      - alert: VaultSealed
        annotations:
          summary: Vault is sealed.
        expr: vault_core_unsealed == 0
        for: 5m
        labels:
          severity: critical
      - alert: VaultHighResponseTime
        annotations:
          summary: The response time of Vault is over 500ms on average over the last 5
            minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
        for: 5m
        labels:
          severity: warning
      - alert: VaultHighResponseTime
        annotations:
          summary: The response time of Vault is over 1s on average over the last 5
            minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
        for: 5m
        labels:
          severity: critical
  grafanaDashboard:
    enabled: true

injector:
  enabled: false
