---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: zennotes

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: zennotes-config-env
    literals:
      - ZENNOTES_BIND=[::]:7878
      - ZENNOTES_ALLOW_INSECURE_NOAUTH=1
      - ZENNOTES_BEHIND_TLS=1
      - ZENNOTES_TRUSTED_PROXIES=2001:67c:17fc:110::/60,172.28.128.0/22

images:
  - name: docker.io/adibhanna/zennotes
    newTag: 2.9.0@sha256:af4a874729914ea8607a241588ccf994a6966dff4a117c3f10ef59cf123a64ba
