---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: zennotes

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: zennotes-config-env
    literals:
      - ZENNOTES_BIND=[::]:7878
      - ZENNOTES_ALLOW_INSECURE_NOAUTH=1
      - ZENNOTES_BEHIND_TLS=1
      - ZENNOTES_TRUSTED_PROXIES=2001:67c:17fc:110::/60,172.28.128.0/22

images:
  - name: docker.io/adibhanna/zennotes
    newTag: 2.49.0@sha256:8f90b620b543c1d62b078cb6e9ac16d9f7b425c1cd504be79a6df492368f44b6
