---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: zennotes

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: zennotes-config-env
    literals:
      - ZENNOTES_BIND=[::]:7878
      - ZENNOTES_ALLOW_INSECURE_NOAUTH=1
      - ZENNOTES_BEHIND_TLS=1
      - ZENNOTES_TRUSTED_PROXIES=2001:67c:17fc:110::/60,172.28.128.0/22

images:
  - name: docker.io/adibhanna/zennotes
    newTag: 2.66.0@sha256:aec76d49e0e597b67abf24342f6a1f7bd581c7f6810632303c5820150a3a4c49
