---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kdc

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: kdc-config
    literals:
      - KRB5_REALM=LAMA-CORP.SPACE
      - KRB5_KDC_MASTER_PASSWORD_FILE=/secrets/master-password

images:
  - name: ghcr.io/authentik-labs/krb5
    newTag: 0.2.5@sha256:240ba4288d2b4fb35bd37acf6f123501320c1ed4a2037c4861a000b435d8ffcb
