---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kdc

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: kdc-config
    literals:
      - KRB5_REALM=LAMA-CORP.SPACE
      - KRB5_KDC_MASTER_PASSWORD_FILE=/secrets/master-password

images:
  - name: ghcr.io/authentik-community/krb5
    newTag: 0.2.2@sha256:f32b99dc76d1b89173875a036c60d383c78d05276eb17109dd089270a4b611bc
