---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: kdc

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: kdc-config
    literals:
      - KRB5_REALM=LAMA-CORP.SPACE
      - KRB5_KDC_MASTER_PASSWORD_FILE=/secrets/master-password

images:
  - name: ghcr.io/authentik-community/krb5
    newTag: 0.2.1@sha256:efe56f3c5bc4288a1793a3c51c8a333e8ed6971d808c5f02e2be2cd1a80a1799
