---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: happydomain

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: happydomain-config
    literals:
      - HAPPYDOMAIN_STORAGE_ENGINE=leveldb
      - HAPPYDOMAIN_LEVELDB_PATH=/data
      - HAPPYDOMAIN_EXTERNALURL=https://dns.as212024.net
      - HAPPYDOMAIN_DISABLE_EMBEDDED_LOGIN=true
      - HAPPYDOMAIN_DISABLE_REGISTRATION=true
      - HAPPYDOMAIN_OIDC_PROVIDER_URL=https://auth.as212024.net/application/o/happydomain/

images:
  - name: docker.io/happydomain/happydomain
    newTag: latest@sha256:7eccf4e9afec930c0a9e1a04b68ea1252e011bbccc4f2495563b63dab647e37b
