---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: happydomain

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: happydomain-config
    literals:
      - HAPPYDOMAIN_STORAGE_ENGINE=leveldb
      - HAPPYDOMAIN_LEVELDB_PATH=/data
      - HAPPYDOMAIN_EXTERNALURL=https://dns.as212024.net
      - HAPPYDOMAIN_DISABLE_EMBEDDED_LOGIN=true
      - HAPPYDOMAIN_DISABLE_REGISTRATION=true
      - HAPPYDOMAIN_OIDC_PROVIDER_URL=https://auth.as212024.net/application/o/happydomain/

images:
  - name: docker.io/happydomain/happydomain
    newTag: latest@sha256:fa7a2f048ef339726ae13d9a31b497df1b42a7e105df29e65278a90eb4b21177
