---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: happydomain

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: happydomain-config
    literals:
      - HAPPYDOMAIN_STORAGE_ENGINE=leveldb
      - HAPPYDOMAIN_LEVELDB_PATH=/data
      - HAPPYDOMAIN_EXTERNALURL=https://dns.as212024.net
      - HAPPYDOMAIN_DISABLE_EMBEDDED_LOGIN=true
      - HAPPYDOMAIN_DISABLE_REGISTRATION=true
      - HAPPYDOMAIN_OIDC_PROVIDER_URL=https://auth.as212024.net/application/o/happydomain/

images:
  - name: docker.io/happydomain/happydomain
    newTag: latest@sha256:4b13188afae4ecad9ea1d0bc560dba1e1d7892b502db8947c997c0bb959c8c0d
