---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-oidc-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-authentik
  dataFrom:
    - extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-external/frigate
      rewrite:
        - regexp:
            source: client_secret
            target: client-secret
