---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: whoisd

resources:
  - deployment.yml
  - network-policy.yml
  - service.yml

images:
  - name: ghcr.io/lamacorp/whoisd
    newTag: v0.2.2@sha256:75ecb4c222656e26e1ffd1386db8dcb244b16be88894de53d33eb04f67bdf276
