---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: whoisd

resources:
  - deployment.yml
  - network-policy.yml
  - service.yml

images:
  - name: ghcr.io/lamacorp/whoisd
    newTag: v0.2.2
