---
netplan_configuration:
  network:
    version: 2
    ethernets:
      ens3:
        mtu: 9000
        addresses:
          - 172.28.1.11/26
          - 2001:67c:17fc:101::11/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.1.62
          - to: ::/0
            via: 2001:67c:17fc:101::1
