---
#### YAML inventory file

## Structure
# hosts:
#   - host: <HOSTNAME>
#     # if needed
#     hostvars:
#       key: value
#     # if needed
#     groups:
#       - group1
#       - group2

hosts:
  - host: nucleus.fsn.as212024.net
    groups:
      - core
      - fsn
      - kvm
      - lb
  - host: gate-1.bar.as212024.net
    groups:
      - bar
      - core
      - dhcp
      - docker
  - host: edge-1.pvl.as212024.net
    groups:
      - core
      - dns
      - pvl
  - host: edge-2.fra.as212024.net
    groups:
      - core
      - dns
      - fra

  - host: mail.fsn.as212024.net
    groups:
      - docker
      - fsn
      - mail
      - vm
  - host: mongodb.fsn.as212024.net
    groups:
      - fsn
      - mongodb
      - vm
  - host: postgresql.fsn.as212024.net
    groups:
      - acme_client
      - fsn
      - postgresql
      - vm
  - host: redis.fsn.as212024.net
    groups:
      - fsn
      - redis
      - vm

  - host: k3s-1.fsn.as212024.net
    groups:
      - fsn
      - k3s
      - vm
  - host: k3s-1.bar.as212024.net
    groups:
      - bar
      - k3s
  - host: k3s-2.bar.as212024.net
    groups:
      - bar
      - k3s

  - host: pine.fsn.as212024.net
    groups:
      - docker
      - fsn
      - vm

  - host: ntp-1.bar.as212024.net
    groups:
      - bar
      - gps

  - host: homeassistant.bar.risson.net
    groups:
      - bar
      - docker
  - host: recorder.bar.risson.net
    groups:
      - bar
      - docker
  - host: caster.bar.risson.net
    groups:
      - bar
      - snapserver
  # - host: ext-1.music.bar.risson.net
  #   groups:
  #     - bar
  #     - bar_music
  #     - snapclient
  # - host: ext-2.music.bar.risson.net
  #   groups:
  #     - bar
  #     - bar_music
  #     - snapclient
  - host: cuisine.music.bar.risson.net
    groups:
      - bar
      - bar_music
      - snapclient
  - host: salle-a-manger.music.bar.risson.net
    groups:
      - bar
      - bar_music
      - snapclient
  - host: sport.music.bar.risson.net
    groups:
      - bar
      - bar_music
      - snapclient
  - host: entree.music.bar.risson.net
    groups:
      - bar
      - bar_music
      - snapclient
  # - host: salon.music.bar.risson.net
  #   groups:
  #     - bar
  #     - bar_music
  #     - snapclient
