---
collections:
  - name: ansible.utils
    version: 6.0.0
  - name: community.docker
    version: 5.0.0
  - name: community.general
    version: 11.4.1
  - name: community.hashi_vault
    version: 7.1.0
  - name: community.mongodb
    version: 1.7.10
  - name: prometheus.prometheus
    version: 0.27.3
  - name: git+https://gitlab.cri.epita.fr/cri/iac/ansible/collections/acme.git
    type: git
    version: 0.5.0

roles:
  - name: aruhier.unbound
    src: git+https://github.com/aruhier/ansible-role-unbound.git
    version: 8c0781a9a014a4abca24cdd3ffb83871c0b15c79
  - name: cri.restic
    src: git+https://gitlab.com/byh0ki-org/infra/ansible/roles/restic.git
    version: 3.2.0
  - name: geerlingguy.docker
    version: 7.8.0
  - name: ipr-cnrs.nftables
    src: git+https://github.com/ipr-cnrs/nftables.git
    version: 68932eed012b9f5d05578f9d52733b633144e022
  - name: mrlesmithjr.netplan
    src: git+https://github.com/rissson/ansible-netplan.git
    version: 9aea84954d03c520496ad011290ebe95e7e82de3
  - name: ome.haproxy
    src: git+https://github.com/rissson/ansible-role-haproxy.git
    version: 2968ced132136ea061b4a74875522a97d7bf3f93
  - name: stackhpc.libvirt-host
    version: v1.14.0
  - name: stackhpc.libvirt-vm
    version: v1.16.3
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.6.1
