---
bird_threads: 8

bird_router_id: 209.112.97.241

bird_bgp_preferred_source:
  v4: 209.112.97.241
  v6: 2001:67c:17fc:ffff::1

bird_static_routes:
  v4:
    - 209.112.97.241/32 via "id"
    # Local routes
    - 37.46.199.160/27 unreachable # netrouting /27
    - 209.112.97.25/32 unreachable # mail.lama-corp.space
    - 209.112.97.54/32 via "svc-ns1" # ns1.as212024.net
    - 209.112.97.232/32 unreachable # nat-svc
    - 209.112.97.233/32 unreachable # nat-mdw
    - 209.112.97.234/32 unreachable # nat-cust
    - 209.112.97.243/32 via "legacy" # legacy ns1
    # Needed for sessions
    - 169.254.6.206/32 via 37.46.199.110%'ul-netr-0' # needed because multihop to netrouting
  v6:
    - 2001:67c:17fc:ffff::1/128 via "id"
    # Local routes
    - 2001:67c:17fc::25/128 unreachable # mail.as212024.net
    - 2001:67c:17fc::54/128 via "svc-ns1" # ns1.as212024.net
    - 2001:67c:17fc:ffff::3/128 via "legacy" # legacy ns1
    - 2a06:e881:7701:2::/64 via "cl-hane-1" # hane-1.client.fra.as212024.net

bird_bgp_originations:
  v4: []
  v6: []

bird_bgp_blacklist:
  v4:
    - 37.46.199.110/31- # Local prefix
  v6:
    - 2a00:dd0:aaaa:a::/64- # Local prefix

bird_bgp_sessions:
  upstreams:
    sessions:
      - description: Netrouting
        alias: netrouting
        asn: 6206
        md5: "BGP@NR1n2026-212024"
        multihop: 2
        local:
          v4: 37.46.199.111
          v6: 2a00:dd0:aaaa:a::2
        remote:
          v4: 169.254.6.206
          v6: fd00:6206:6206::1
        med_metric: true
        default_med: 100

  peers:
    sessions:
      - description: James Landrein 1
        alias: james_landrein_1
        asn: 201254
        irr: AS201254
        interface: ppl-as201254-1
        local:
          v6: fd68:2402:1fbb:e377::1:21:2024
        remote:
          v6: fd68:2402:1fbb:e377::1:20:1254
      - description: James Landrein 2
        alias: james_landrein_2
        asn: 201254
        irr: AS201254
        interface: ppl-as201254-2
        local:
          v6: fd68:2402:1fbb:e377::2:21:2024
        remote:
          v6: fd68:2402:1fbb:e377::2:20:1254

  cores:
    defaults:
      med_metric: true
    sessions:
      - description: FRA
        alias: fra
        asn: 212024
        interface: core-fra
        local:
          v4: 169.254.0.4
          v6: fe80::0:4
        remote:
          v4: 169.254.0.5
          v6: fe80::0:5

bird_ospf_sessions:
  - alias: ospf
    export_static_routes: true
    areas:
      0.0.0.0:
        interfaces:
          core-bar:
            type: ptp
            cost: 25
          core-fra:
            type: ptp
            cost: 25
          lan-svc-101:
            cost: 1
          lan-mdw-102:
            stub: true
