---
kind: Kustomization

nameSuffix: "-2022"

commonLabels:
  app.kubernetes.io/version: "2022"

resources:
  - ../../base

patches:
  - path: service.yml

images:
  - name: docker.io/factoriotools/factorio
    newTag: 1.1.110
    digest: sha256:6fb9b7bfb12fb51bf668fce7e29cb1e98053f248201e64dfee870ef73b2f31cb
