---
kind: Kustomization

nameSuffix: "-2022"

commonLabels:
  app.kubernetes.io/version: "2022"

resources:
  - ../../base

patches:
  - path: service.yml

images:
  - name: docker.io/factoriotools/factorio
    newTag: 2.1.17@sha256:e9227748c507a52f97bbd42c88e5c73702297bbdf4322c2f3ca8a71676ec1222
