---
kind: Kustomization

nameSuffix: "-2022"

commonLabels:
  app.kubernetes.io/version: "2022"

resources:
  - ../../base

patches:
  - path: service.yml

images:
  - name: factoriotools/factorio
    newTag: 2.0.73@sha256:6471fbfb7eab3abf55bb53fed632606ecf17bf930891bccddff724afab9ed94c
