---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: microbin

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - service.yml

configMapGenerator:
  - name: microbin-config
    literals:
      - "MICROBIN_BIND=::"
      - MICROBIN_ADMIN_USERNAME=
      - MICROBIN_EDITABLE=true
      - MICROBIN_PRIVATE=true
      - MICROBIN_PUBLIC_PATH=https://bin.lama-corp.space
      - MICROBIN_THREADS=2
      - MICROBIN_ENABLE_BURN_AFTER=true
      - MICROBIN_QR=true
      - MICROBIN_ETERNAL_PASTA=false
      - MICROBIN_DEFAULT_EXPIRY=1week
      - MICROBIN_ENCRYPTION_CLIENT_SIDE=true
      - MICROBIN_ENCRYPTION_SERVER_SIDE=true
      - MICROBIN_DISABLE_UPDATE_CHECKING=true
      - MICROBIN_DISABLE_TELEMETRY=true
      - MICROBIN_LIST_SERVER=false

images:
  - name: docker.io/danielszabo99/microbin
    newTag: 2.1.2@sha256:4e08d1d127e5804f5e43a63c0c9555497d506ee94abb570214134b73a4810f62
