---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: actual
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: budget.risson.space
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: actual-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: actual
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: actual
  hostnames:
    - budget.risson.space
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: actual
          port: 80
      timeouts:
        request: 60s
        backendRequest: 60s
