---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-oidc-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-authentik
  target:
    template:
      engineVersion: v2
      data:
        ACTUAL_OPENID_CLIENT_ID: "{{ .client_id }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-actual-risson
