---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: stirling-pdf

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: stirling-pdf-config-env
    literals:
      - SYSTEM_DEFAULTLOCALE=fr-FR
      - SYSTEM_GOOGLEVISIBILITY=false
      - SYSTEM_SHOWUPDATE=false

      - UI_APPNAME=PDF
      - UI_HOMEDESCRIPTION=Manipuler vos PDFs avec aisance
      - UI_APPNAMENAVBAR=PDF

      - METRICS_ENABLED=true

      - SECURITY_ENABLELOGIN=false

images:
  - name: docker.io/stirlingtools/stirling-pdf
    newTag: 2.10.0-fat@sha256:ae61bf189cdb2ae691be80d97e8ec62ec1fbae710f3fb5c3b9f3bcfb6ef8bafc
