---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: stirling-pdf

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: stirling-pdf-config-env
    literals:
      - SYSTEM_DEFAULTLOCALE=fr-FR
      - SYSTEM_GOOGLEVISIBILITY=false
      - SYSTEM_SHOWUPDATE=false

      - UI_APPNAME=PDF
      - UI_HOMEDESCRIPTION=Manipuler vos PDFs avec aisance
      - UI_APPNAMENAVBAR=PDF

      - METRICS_ENABLED=true

      - SECURITY_ENABLELOGIN=false

images:
  - name: docker.io/stirlingtools/stirling-pdf
    newTag: 2.13.1-fat@sha256:e5731460b0545eba75f0af04d86954713fd768d0f51f89ebfb6e70b6d89b2f48
