---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: stirling-pdf

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: stirling-pdf-config-env
    literals:
      - SYSTEM_DEFAULTLOCALE=fr-FR
      - SYSTEM_GOOGLEVISIBILITY=false
      - SYSTEM_SHOWUPDATE=false

      - UI_APPNAME=PDF
      - UI_HOMEDESCRIPTION=Manipuler vos PDFs avec aisance
      - UI_APPNAMENAVBAR=PDF

      - METRICS_ENABLED=true

      - SECURITY_ENABLELOGIN=false

images:
  - name: docker.io/stirlingtools/stirling-pdf
    newTag: 2.14.0-fat@sha256:d44d101a25a5a6e5f4d706bb37788678c0d514332f144ef9c65984d14c078199
