---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-your-spotify-mongodb-credentials
spec:
  path: /mongodb/static-creds/mongodb.fsn.as212024.net_k3s.fsn.as212024.net_services-your-spotify
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: your-spotify-mongodb-credentials
spec:
  refreshInterval: 1m
  target:
    template:
      engineVersion: v2
      data:
        MONGO_ENDPOINT: "mongodb://{{ .username }}:{{ .password }}@mongodb.fsn.as212024.net/yourSpotify"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-your-spotify-mongodb-credentials
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.as212024.net
      path: k8s-k3s.fsn.as212024.net
      auth:
        kubernetes:
          mountPath: k8s-k3s.fsn.as212024.net
          role: common
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: your-spotify-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-your-spotify/secrets
