---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: netbox

resources:
  - server
  - worker
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: netbox-config
    files:
      - config/configuration.py
  - name: netbox-oauth-custom-pipline
    files:
      - config/custom_pipeline.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.5.6@sha256:c0cab426c53a3cae49436a858fccd340ccf2eb5b3d5e1a72c61818b88fd56c3f
