---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: netbox

resources:
  - server
  - worker
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: netbox-config
    files:
      - config/configuration.py
  - name: netbox-oauth-custom-pipline
    files:
      - config/custom_pipeline.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.6.1@sha256:845b3e722bb87d0604bd336eec9eaaa6c2c82bcec49ea659905b9b09783a1634
