---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: netbox

resources:
  - server
  - worker
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: netbox-config
    files:
      - config/configuration.py
  - name: netbox-oauth-custom-pipline
    files:
      - config/custom_pipeline.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.6.0@sha256:3ede2e649ac895e7661a41317364dfe84ecadbe849a6d07fc09bef975835572e
