---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-envoy-gateway
  labels:
    app: core-envoy-gateway
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: core-envoy-gateway-{{ .name }}
      labels:
        app: core-envoy-gateway
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: core-eg
      source:
        repoURL: docker.io/envoyproxy
        targetRevision: 1.5.4
        chart: gateway-helm
        helm:
          releaseName: envoy-gateway
          skipCrds: true
          values: |
            kubernetesClusterDomain: "c.{{ .name }}"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-envoy-gateway-crds
  labels:
    app: core-envoy-gateway
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: core-envoy-gateway-crds-{{ .name }}
      labels:
        app: core-envoy-gateway
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: core-eg
      source:
        repoURL: https://github.com/envoyproxy/gateway.git
        targetRevision: v1.6.0
        path: charts/gateway-helm/crds/generated
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-envoy-gateway-extra
  labels:
    app: core-envoy-gateway
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: core-envoy-gateway-extra-{{ .name }}
      labels:
        app: core-envoy-gateway
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: core-eg
      source:
        repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
        targetRevision: HEAD
        path: k8s/core/envoy-gateway/extra/{{ .name }}
