---
netplan_configuration:
  network:
    version: 2
    ethernets:
      eth0:
        mtu: 9000
        addresses:
          - 172.28.2.65/27
          - 2001:67c:17fc:204::123/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.2.94
          - to: ::/0
            via: 2001:67c:17fc:204::1
    dummy-devices:
      public:
        mtu: 9000
        addresses:
          - 209.112.97.123/32
          - 2001:67c:17fc::123/128
