---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: zigbee2mqtt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: z2m.phemma.fr
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: zigbee2mqtt-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zigbee2mqtt
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: zigbee2mqtt
  hostnames:
    - z2m.phemma.fr
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: zigbee2mqtt
          port: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: zigbee2mqtt
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: zigbee2mqtt
  oidc:
    provider:
      issuer: https://auth.lama-corp.space/application/o/zigbee2mqtt/
    clientID: zigbee2mqtt
    clientSecret:
      name: zigbee2mqtt-oidc-credentials
    scopes:
      - offline_access
    refreshToken: true
