---
netplan_configuration:
  network:
    version: 2
    ethernets:
      ens3:
        mtu: 1420
        addresses:
          - 172.28.1.120/26
          - 2001:67c:17fc:102::120/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.1.126
          - to: ::/0
            via: 2001:67c:17fc:102::1
