---
backup_restic_creds_mongodb: "{{ lookup('community.hashi_vault.hashi_vault', 'restic/data/repositories/' + inventory_hostname + '/mongodb') }}"

backup_restic_list_raw:
  - name: mongodb
    enabled: true
    repo_password: "{{ backup_restic_creds_mongodb['repo_password'] }}"
    backend:
      type: wasabi
      s3_bucket_name: "{{ backup_restic_creds_mongodb['bucket_name'] }}"
      s3_access_key: "{{ backup_restic_creds_mongodb['backup_access_key'] }}"
      s3_secret_key: "{{ backup_restic_creds_mongodb['backup_secret_key'] }}"
      s3_prune_access_key: "{{ backup_restic_creds_mongodb['prune_access_key'] }}"
      s3_prune_secret_key: "{{ backup_restic_creds_mongodb['prune_secret_key'] }}"
    to_include:
      - /var/lib/mongodb/backup.archive
    backup_pre_hooks:
      - cmd:
          - "bash"
          - "-c"
          - "rm -f /var/lib/mongodb/backup.archive && mongodump --username={{ mongodb_admin_user }} --password={{ mongodb_admin_pwd }} --archive=/var/lib/mongodb/backup.archive"
    backup_systemd_timers:
      minute: 02
      hour: 05
    prune_systemd_timers:
      minute: 14
      hour: 13
