---
redis_enable_vm_overcommit: true

# sort by port number
redis_instances:
  - name: authentik
    port: 6380
  - name: nextcloud
    port: 6382
  - name: paperless_risson
    port: 6383
  - name: matrix_synapse
    port: 6384
  - name: netbox
    port: 6385
  - name: immich
    port: 6386
  - name: mastodon
    port: 6388
