---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-rocketchat
  labels:
    app: services-rocketchat
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: lama
          - name: sdlh
  template:
    metadata:
      name: "services-rocketchat-{{ .name }}"
      labels:
        app: services-rocketchat
    spec:
      project: services
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: k3s.fsn.as212024.net
        namespace: "services-rocketchat-{{ .name }}"
      sources:
        - repoURL: https://github.com/LamaCorp/infrastructure.git
          targetRevision: HEAD
          ref: infrastructure
        - repoURL: https://github.com/rissson/rocketchat-helm-charts.git
          targetRevision: deployment-annotations
          path: rocketchat
          helm:
            releaseName: rocketchat
            valueFiles:
              - "$infrastructure/k8s/services/rocketchat/values.yml"
              - "$infrastructure/k8s/services/rocketchat/{{ .name }}-values.yml"
        - repoURL: https://github.com/LamaCorp/infrastructure.git
          targetRevision: HEAD
          path: "k8s/services/rocketchat/extra/{{ .name }}"
