---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-rocketchat
  labels:
    app: services-rocketchat
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: lama
          - name: sdlh
  template:
    metadata:
      name: "services-rocketchat-{{ .name }}"
      labels:
        app: services-rocketchat
    spec:
      project: services
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
      destination:
        name: k3s.fsn.as212024.net
        namespace: "services-rocketchat-{{ .name }}"
      sources:
        - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
          targetRevision: HEAD
          path: "k8s/services/rocketchat/extra/{{ .name }}"
        - repoURL: https://github.com/rissson/rocketchat-helm-charts.git
          targetRevision: deployment-annotations
          path: rocketchat
          helm:
            releaseName: rocketchat
            values: |
              image:
                repository: registry.rocket.chat/rocketchat/rocket.chat
                tag: 8.1.1

              deploymentAnnotations:
                secret.reloader.stakater.com/reload: rocketchat-mongodb-credentials

              existingMongodbSecret: rocketchat-mongodb-credentials

              extraEnv:
                - name: BIND_IP
                  value: "::"

                - name: OVERWRITE_SETTING_SMTP_Protocol
                  value: smtps
                - name: OVERWRITE_SETTING_SMTP_Host
                  value: email-smtp.eu-west-3.amazonaws.com
                - name: OVERWRITE_SETTING_SMTP_Port
                  value: "465"
                - name: OVERWRITE_SETTING_SMTP_Username
                  valueFrom:
                    secretKeyRef:
                      name: rocketchat-smtp-credentials
                      key: username
                - name: OVERWRITE_SETTING_SMTP_Password
                  valueFrom:
                    secretKeyRef:
                      name: rocketchat-smtp-credentials
                      key: password
                - name: OVERWRITE_SETTING_From_Email
                  value: no-reply-chat@lama-corp.space

                - name: OVERWRITE_SETTING_Accounts_OAuth_Custom-Authentik-id
                  valueFrom:
                    secretKeyRef:
                      name: rocketchat-oidc-credentials
                      key: client_id
                - name: OVERWRITE_SETTING_Accounts_OAuth_Custom-Authentik-secret
                  valueFrom:
                    secretKeyRef:
                      name: rocketchat-oidc-credentials
                      key: client_secret

              microservices:
                enabled: false
              nats:
                enabled: false

              persistence:
                enabled: true

              mongodb:
                enabled: false
