---
netplan_configuration:
  network:
    version: 2
    ethernets:
      eno1:
        mtu: 9000
        addresses:
          - 172.28.2.194/27
          - 2001:67c:17fc:207::194/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.2.222
          - to: ::/0
            via: 2001:67c:17fc:207::1
    vlans:
      bar-cctv:
        id: 2094
        link: eno1
        mtu: 1500
        accept-ra: false
        addresses:
          - 172.29.194.1/24
          - 2a06:e881:7701:194::5000/64
