---
# common

root_password_hashed: "$6$RQ1LcccPWB/NO5V.$TWZLJnGGSF1CarIAZhT5YiK.mTLLrbnnVIxwzkCOXa39.WtSjLW7m99ARoPg8iyMzid7EUetecBBbqahyLWfH/"

# chrony

chrony_config:
  server:
    - core-1.fra.as212024.net iburst xleave extfield F323 {% if "fsn" in group_names %}prefer{% endif %}
    - gate-1.bar.as212024.net iburst xleave extfield F323 {% if "bar" in group_names %}prefer{% endif %}
    - edge-1.pvl.as212024.net iburst xleave extfield F323 {% if "pvl" in group_names %}prefer{% endif %}
    - edge-2.fra.as212024.net iburst xleave extfield F323 {% if "fra" in group_names %}prefer{% endif %}
  initstepslew: 10 ntp1.as212024.net ntp2.as212024.net pool.ntp.org
  makestep: 0.1 3
  dscp: 46

chrony_exporter_enabled_collectors:
  - tracking
  - sources
  - serverstats
chrony_exporter_disabled_collectors:
  - dns-lookups

# nftables

nft_filter_input_policy: drop
nft_filter_input_default_verdict: accept
nft_filter_forward_policy: drop
nft_filter_forward_default_verdict: accept

# node exporter

node_exporter_version: latest
node_exporter_textfile_dir: /var/lib/node_exporter
node_exporter_enabled_collectors:
  - cgroups
  - ethtool
  - logind
  - ntp
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"

# vault

vault_addr: https://vault.as212024.net:443
vault_version: 1.13.0

# textfile collectors

node_exporter_textfile_collector_scripts_to_install:
  - apt_info.py
  - deleted_libraries.py
  - smartmon.py

# Fix for debian trixie. Doesn't break bookworm

netplan_packages:
  - netplan.io
