---
network_nameservers:
  - 1.1.1.1
  - 1.0.0.1

systemd_networkd_config:
  10-default:
    Network:
      ManageForeignRoutes: false
      ManageForeignRoutingPolicyRules: false
      ManageForeignNextHops: false
      IPv4Forwarding: true
      IPv6Forwarding: true

netplan_config_file: /etc/netplan/00-network.yaml
netplan_remove_existing: true

netplan_renderer: networkd

whois_server: whois.as212024.net

bird_asn: 212024
