---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: atuin

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - secrets.yml
  - service.yml

images:
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.13.6@sha256:9bde3fe6b1633c357cb19c07ea49bb9834720e8ff42d04b39ad7865155581150
