---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: atuin

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - secrets.yml
  - service.yml

images:
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.23.0@sha256:f232feeead54a0a13132b9cd477e312c3380e9dc90f1db24c4f79ce6c8e034ea
