---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: atuin

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - secrets.yml
  - service.yml

images:
  - name: ghcr.io/atuinsh/atuin
    newTag: 18.21.0@sha256:38c6c323c6d3864250dc345dcf9d41b7a408ee6e33a7cc3cde44b6ffe9f64a02
