---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-atuin-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-atuin
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-postgres-credentials
spec:
  refreshInterval: 1m
  target:
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: "postgres://{{ .username }}:{{ .password }}@postgresql.fsn.as212024.net:6432/atuin"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-atuin-postgres-credentials
