---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: rocketchat

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

images:
  - name: registry.rocket.chat/rocketchat/rocket.chat
    newTag: 8.4.2@sha256:f7d6e0c1778fdda39f92398607cff8ef54eae36598bba9ece4968fad67b96ecc
