---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: rocketchat

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

images:
  - name: registry.rocket.chat/rocketchat/rocket.chat
    newTag: 8.5.1@sha256:91737a0c7b832f4f995097786f16e68c2311cf8d7b92071d70287d8ff436612d
