---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: rocketchat

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

images:
  - name: registry.rocket.chat/rocketchat/rocket.chat
    newTag: 8.9.0@sha256:295f7b2c38fc3542024dc404f887eb2e13276b66e5854d31d86bcd069f6ce6dc
