---
netplan_configuration:
  network:
    version: 2
    ethernets:
      end0:
        mtu: 9000
        addresses:
          - 172.28.2.193/27
          - 2001:67c:17fc:207::193/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.2.222
          - to: ::/0
            via: 2001:67c:17fc:207::1
    vlans:
      bar-music:
        mtu: 9000
        id: 2093
        link: end0
        addresses:
          - 172.29.193.1/24
          - 2a06:e881:7701:193::1704/64
      bar-client:
        mtu: 1500
        id: 2050
        link: end0
        accept-ra: false
        addresses:
          - 172.29.2.193/24
