protocol static static4 {
  ipv4;

  {% for route in bird_static_routes.v4 | default([]) %}
  route {{ route }};
  {% endfor %}
}

protocol static static6 {
  ipv6;

  {% for route in bird_static_routes.v6 | default([]) %}
  route {{ route }};
  {% endfor %}
}

protocol static local4 {
  ipv4;
  {% for route in bird_local_routes.v4 | default([]) %}
  route {{ route }};
  {% endfor %}
}

protocol static local6 {
  ipv6;

  {% for route in bird_local_routes.v6 | default([]) %}
  route {{ route }};
  {% endfor %}
}
