---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictrs
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 27831
        runAsGroup: 27831
        fsGroup: 27831
      containers:
        - name: pictrs
          image: asonix/pictrs
          env:
            - name: PICTRS__SERVER__API_KEY
              valueFrom:
                secretKeyRef:
                  name: lemmy-pictrs
                  key: api_key
          envFrom:
            - configMapRef:
                name: pictrs-config
            - secretRef:
                name: pictrs-postgres-credentials
          volumeMounts:
            - name: data
              mountPath: /mnt
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     port: http
          #     path: /healthz
          # readinessProbe:
          #   httpGet:
          #     port: http
          #     path: /healthz
          # startupProbe:
          #   httpGet:
          #     port: http
          #     path: /healthz
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lemmy-pictrs-data
