---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: mastodon
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: social.lama-corp.space
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: mastodon-https
    - name: webfinger
      hostname: lama-corp.space
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: mastodon-webfinger-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: mastodon
  hostnames:
    - social.lama-corp.space
  rules:
    - matches:
        - path:
            value: /api/v1/streaming
      backendRefs:
        - name: mastodon-streaming
          port: 80
    - matches:
        - path:
            value: /
      backendRefs:
        - name: mastodon-web
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-webfinger
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: mastodon
  hostnames:
    - lama-corp.space
  rules:
    - matches:
        - path:
            value: /.well-known/webfinger
        - path:
            value: /.well-known/host-meta
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Access-Control-Allow-Origin
                value: "*"
        - type: RequestRedirect
          requestRedirect:
            hostname: social.lama-corp.space
            statusCode: 301
