---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-gatus-zarak
  labels:
    app: services-gatus-zarak
spec:
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: services-gatus-zarak
  sources:
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      ref: infrastructure
    - repoURL: https://twin.github.io/helm-charts
      targetRevision: 1.5.0
      chart: gatus
      helm:
        releaseName: gatus
        valueFiles:
          - $infrastructure/k8s/services/gatus/zarak-values.yml
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      path: k8s/services/gatus/extra/zarak
