---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-gatus-zarak
  labels:
    app: services-gatus-zarak
spec:
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: services-gatus-zarak
  sources:
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      path: k8s/services/gatus/extra/zarak
    - repoURL: https://twin.github.io/helm-charts
      targetRevision: 1.5.0
      chart: gatus
      helm:
        releaseName: gatus
        values: |
          image:
            repository: twinproduction/gatus
            tag: v5.35.0

          annotations:
            reloader.stakater.com/auto: "true"

          # Does envFrom secret named gatus
          secrets: true

          serviceMonitor:
            enabled: true

          gateway:
            route:
              enabled: true
              parentRefs:
                - name: eg-http-public
                  namespace: core-eg
                  sectionName: https
              hosts:
                - zarak.devou.ps

          config:
            web:
              address: "[::]"
            metrics: true

            storage:
              type: postgres
              path: "postgres://${DB_USER}:${DB_PASS}@postgresql.fsn.as212024.net:6432/gatus_zarak?sslmode=require"

            ui:
              title: Zarak
              header: Zarak external infrastructure monitoring
              logo: https://zarak.fr/resources/cyril-avatar.jpg
              link: https://zarak.fr

            .defaults: &defaults
              interval: 30s

            .https-endpoint: &https-endpoint
              <<: *defaults
              conditions:
                - "[STATUS] == 200"
                - "[RESPONSE_TIME] <= 2000"
                - "[CERTIFICATE_EXPIRATION] > 168h" # 7 days

            endpoints:

              - name: zarak.fr
                <<: *https-endpoint
                url: https://zarak.fr

              - name: cyrilduval.fr
                <<: *https-endpoint
                url: https://cyrilduval.fr
