---
image:
  repository: twinproduction/gatus
  tag: v5.37.0@sha256:094eb186e55235db367e90e9d56140e5897b7044c41de23cde4cc18e6da1242e

annotations:
  reloader.stakater.com/auto: "true"

# Does envFrom secret named gatus
secrets: true

serviceMonitor:
  enabled: true

gateway:
  route:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: ListenerSet
        name: gatus
    hosts:
      - zarak.devou.ps

config:
  web:
    address: "[::]"
  metrics: true

  storage:
    type: postgres
    path: "postgres://${DB_USER}:${DB_PASS}@postgresql.fsn.as212024.net:6432/gatus_\
      zarak?sslmode=require"

  ui:
    title: Zarak
    header: Zarak external infrastructure monitoring
    logo: https://zarak.fr/resources/cyril-avatar.jpg
    link: https://zarak.fr

  .defaults: &defaults
    interval: 30s

  .https-endpoint: &https-endpoint
    <<: *defaults
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] <= 2000"
      - "[CERTIFICATE_EXPIRATION] > 168h" # 7 days

  endpoints:

    - name: zarak.fr
      <<: *https-endpoint
      url: https://zarak.fr

    - name: cyrilduval.fr
      <<: *https-endpoint
      url: https://cyrilduval.fr
