---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: your-spotify-web
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: your-spotify
  hostnames:
    - ys.lama-corp.space
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: your-spotify-web
          port: 80
