---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-gitlab-runner
  labels:
    app: services-gitlab-runner
spec:
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: services-gitlab-runner
  sources:
    - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
      targetRevision: HEAD
      path: k8s/services/gitlab-runner/extra
    - repoURL: https://charts.gitlab.io
      targetRevision: 0.84.0
      chart: gitlab-runner
      helm:
        releaseName: gitlab-runner-lama-corp
        values: |
          gitlabUrl: https://gitlab.com
          concurrent: 4

          rbac:
            create: true

          runners:
            config: |
              [[runners]]
                [runners.kubernetes]
                  namespace = "services-gitlab-runner"
                  image = "alpine"
                  allowed_pull_policies = ["always", "if-not-present"]
            secret: gitlab-runner-secret-lama-corp

          service:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
