---
kind: Kustomization

resources:
  - ../base
  - secrets.yml

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: ListenerSet
      name: rocketchat
    patch: |-
      - op: replace
        path: /spec/listeners/0/hostname
        value: chat-new.lama-corp.space
  - path: httproute.yml
