---
kind: Kustomization

nameSuffix: "-2024"

commonLabels:
  app.kubernetes.io/version: "2024"

resources:
  - ../../base

patches:
  - path: service.yml

images:
  - name: docker.io/factoriotools/factorio
    newTag: 2.0.76@sha256:3cd46d3e7fb8434b74817da202480d8fb89a1ed29d5ab07f8e3ff6781450e936
