---
kind: Kustomization

nameSuffix: "-2024"

commonLabels:
  app.kubernetes.io/version: "2024"

resources:
  - ../../base

patches:
  - path: service.yml

images:
  - name: docker.io/factoriotools/factorio
    newTag: 2.0.76@sha256:0bd437f2bcd63af04d07b7722943f3d362060db821f6d811c7bcae997a019eeb
