---
kind: Kustomization

nameSuffix: "-2024"

commonLabels:
  app.kubernetes.io/version: "2024"

resources:
  - ../../base

patches:
  - path: deployment.yml
  - path: service.yml

images:
  - name: docker.io/factoriotools/factorio
    newTag: 2.1.19@sha256:18c07a80cacce03ebe22d1b36ee8f02225127886dbe20747b696c1498f55fde6
