---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  annotations:
    io.cilium/lb-ipam-ips: 209.112.97.171,2001:67c:17fc:130::2:7015
    external-dns.alpha.kubernetes.io/hostname: 2024.factorio.games.lama-corp.space
