---
nftables_exporter_host_arch_map:
  aarch64: arm64
  x86_64: amd64
nftables_exporter_host_arch: "{{ nftables_exporter_host_arch_map[ansible_architecture] }}"

nftables_exporter_version: v0.4.5
nftables_exporter_checksum_map:
  amd64: 6c72960834e54cceb9791e8db01c8903b78ee7f3cc60a06c61aca790de126fa9
  arm64: 168363163bfef149c64f979a356a14aa780d5e616dea1ad9ec7ee8aa83e62376
nftables_exporter_checksum: "{{ nftables_exporter_checksum_map[nftables_exporter_host_arch] }}"

nftables_exporter_default_config:
  bind_to: "[::]:9630"
  url_path: "/metrics"
  nft_location: /sbin/nft
  log_level: warn
nftables_exporter_config: {}
nftables_exporter_computed_config: "{{ nftables_exporter_default_config | combine(nftables_exporter_config) }}"
