---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: actual

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: actual-config
    literals:
      - ACTUAL_LOGIN_METHOD=openid
      - ACTUAL_ALLOWED_LOGIN_METHODS=openid
      - ACTUAL_TRUSTED_PROXIES=172.28.128.0/22,2001:67c:17fc:110::/60
      - ACTUAL_OPENID_ENFORCE=true
      - ACTUAL_USER_CREATION_MODE=login

images:
  - name: ghcr.io/actualbudget/actual
    newTag: 26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
