# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: Apps - Immich
entries:
  - id: scope-mapping-role
    model: authentik_providers_oauth2.scopemapping
    identifiers:
      name: "OAuth mapping: OpenID 'immich_role'"
    attrs:
      scope_name: immich_roles
      description: Immich roles
      expression: |
        return {
          "immich_role": [
            entitlement.name
            for entitlement in
            request.user.app_entitlements(provider.application)
          ],
        }

  - id: provider
    model: authentik_providers_oauth2.oauth2provider
    identifiers:
      name: k8s/k3s.fsn.as212024.net/services-immich
    attrs:
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-authorization-implicit-consent"],
        ]
      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, "authentik Self-signed Certificate"],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-invalidation-flow"],
        ]

      client_type: confidential
      redirect_uris:
        - url: https://photos.lama-corp.space/auth/login
          matching_mode: strict
        - url: https://photos.lama-corp.space/user-settings
          matching_mode: strict
        - url: app.immich:///oauth-callback
          matching_mode: strict

      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30

      sub_mode: hashed_user_id
      property_mappings:
        - !Find [
            authentik_core.propertymapping,
            [name, "authentik default OAuth Mapping: OpenID 'openid'"],
          ]
        - !Find [
            authentik_core.propertymapping,
            [name, "authentik default OAuth Mapping: OpenID 'profile'"],
          ]
        - !Find [
            authentik_core.propertymapping,
            [name, "OAuth mapping: OpenID 'email' with mailPrimaryAddress"],
          ]
        - !KeyOf scope-mapping-role

  - id: application
    model: authentik_core.application
    identifiers:
      slug: immich
    attrs:
      name: Photos
      group: Stockage
      meta_description: Gestion de photos, vidéos et albums
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
      provider: !KeyOf provider
      policy_engine_mode: any

  - id: group-admin
    model: authentik_core.group
    identifiers:
      name: app-immich-admin
  - id: group-user
    model: authentik_core.group
    identifiers:
      name: app-immich-user

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf application
      group: !KeyOf group-admin
    attrs:
      order: 10
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf application
      group: !KeyOf group-user
    attrs:
      order: 20

  - id: ent-admin
    model: authentik_core.applicationentitlement
    identifiers:
      app: !KeyOf application
      name: admin
  - id: ent-user
    model: authentik_core.applicationentitlement
    identifiers:
      app: !KeyOf application
      name: user

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf ent-admin
      group: !KeyOf group-admin
    attrs:
      order: 10
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf ent-user
      group: !KeyOf group-user
    attrs:
      order: 20
