# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable
---
version: 1
metadata:
  name: Apps - Dawarich
entries:
  - id: provider
    model: authentik_providers_oauth2.oauth2provider
    identifiers:
      name: k8s/k3s.fsn.as212024.net/services-dawarich
    attrs:
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-authorization-implicit-consent"],
        ]
      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, "authentik Self-signed Certificate"],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-invalidation-flow"],
        ]

      client_type: confidential
      redirect_uris:
        - url: https://tracks.lama-corp.space/users/auth/openid_connect/callback
          matching_mode: strict

      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30

      sub_mode: hashed_user_id
      property_mappings:
        - !Find [
            authentik_core.propertymapping,
            [name, "authentik default OAuth Mapping: OpenID 'openid'"],
          ]
        - !Find [
            authentik_core.propertymapping,
            [name, "authentik default OAuth Mapping: OpenID 'profile'"],
          ]
        - !Find [
            authentik_core.propertymapping,
            [name, "OAuth mapping: OpenID 'email' with mailPrimaryAddress"],
          ]

  - id: application
    model: authentik_core.application
    identifiers:
      slug: dawarich
    attrs:
      name: Tracks
      group: Stockage
      meta_description: Tracker d'historique de position
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/dawarich.png
      provider: !KeyOf provider
      policy_engine_mode: any

  - id: group
    model: authentik_core.group
    identifiers:
      name: app-dawarich

  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf application
      group: !KeyOf group
    attrs:
      order: 10
