---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: immich

resources:
  - server
  - microservices
  - machine-learning
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: immich-config-env
    literals:
      - DB_HOSTNAME=postgresql.fsn.as212024.net
      - DB_DATABASE_NAME=immich
      - DB_USERNAME_FILE=/postgres-creds/username
      - DB_PASSWORD_FILE=/postgres-creds/password
      - REDIS_HOSTNAME=redis.fsn.as212024.net
      - REDIS_PORT=6386
      - IMMICH_MEDIA_LOCATION=/data
      - IMMICH_CONFIG_FILE=/config/immich.json
      - TZ=Europe/Paris
  - name: immich-config
    files:
      # See https://github.com/immich-app/immich/blob/main/server/src/config.ts
      - ./config/immich.json

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.3@sha256:0cc1f82953d9598eb9e9dd11cbde1f50fe54f9c46c4506b089e8ad7bfc9d1f0c
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.3@sha256:33b17015c3d14f2565e9b8cd36b48a70027b14b5cd20da7fbfff21a370b0309c
