---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: immich

resources:
  - server
  - microservices
  - machine-learning
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: immich-config-env
    literals:
      - DB_HOSTNAME=postgresql.fsn.as212024.net
      - DB_DATABASE_NAME=immich
      - DB_USERNAME_FILE=/postgres-creds/username
      - DB_PASSWORD_FILE=/postgres-creds/password
      - REDIS_HOSTNAME=redis.fsn.as212024.net
      - REDIS_PORT=6386
      - IMMICH_MEDIA_LOCATION=/data
      - IMMICH_CONFIG_FILE=/config/immich.json
      - TZ=Europe/Paris
  - name: immich-config
    files:
      # See https://github.com/immich-app/immich/blob/main/server/src/config.ts
      - ./config/immich.json

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v3.2.0@sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.2.0@sha256:f8b2869891c861a58dde969d86e7ea8a186e6059a55886632ee3249e51fb574a
