---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: immich

resources:
  - server
  - microservices
  - machine-learning
  - network-policy.yml
  - pvc.yml
  - secrets.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: immich-config-env
    literals:
      - DB_HOSTNAME=postgresql.fsn.as212024.net
      - DB_DATABASE_NAME=immich
      - DB_USERNAME_FILE=/postgres-creds/username
      - DB_PASSWORD_FILE=/postgres-creds/password
      - REDIS_HOSTNAME=redis.fsn.as212024.net
      - REDIS_PORT=6386
      - IMMICH_MEDIA_LOCATION=/data
      - IMMICH_CONFIG_FILE=/config/immich.json
      - TZ=Europe/Paris
  - name: immich-config
    files:
      # See https://github.com/immich-app/immich/blob/main/server/src/config.ts
      - ./config/immich.json

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.2@sha256:1521a1c8c1727ec240e57585db7bf90a3b067066d4847baeb80f353d721f4d5a
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.2@sha256:2d2d56d12d32b904a86952dd048224d117251d10ed10a4d75279e080e79002b7
