---
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: ns0

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - service.yml
  - secrets.yml

configMapGenerator:
  - files:
      - config/knot.conf
    name: knot-dns-config

images:
  - name: docker.io/cznic/knot
    newTag: v3.5.3
    digest: sha256:b5529c82e673fa2ee0505049c681b7f404d50bff7affcb023cfcf2c7ed298903
