---
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: ns0

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - service.yml
  - secrets.yml

configMapGenerator:
  - files:
      - config/knot.conf
    name: knot-dns-config

images:
  - name: docker.io/cznic/knot
    newTag: v3.5.4@sha256:6b352633f3d29001c5a63626abf609b2c2fbaf4e6d06afc4ecc7ed112645175a
