---
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: ns0

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml
  - service.yml
  - secrets.yml

configMapGenerator:
  - files:
      - config/knot.conf
    name: knot-dns-config

images:
  - name: docker.io/cznic/knot
    newTag: v3.5.6@sha256:0974e627c207aa398eaae2a1d1915d2fa26d73621f660dc397ffe9d7a29aceec
