[config]
local-keys = [
  "server.*",
  "!server.allowed-ip.*",
  "!server.blocked-ip.*",
  "http.*",
  "storage.*",
  "store.*",
  "directory.*",
  "session.*",
  "auth.*",
  "queue.*",
  "spam-filter.*",
  "resolver.*",
  "report.*",
  "tracer.*",
  "authentication.fallback-admin.*",
  "authentication.master.*",
]

[server]
hostname = "mail.lama-corp.space"

[server.listener.http]
protocol = "http"
bind = "[::]:80"
[server.listener.https]
protocol = "http"
bind = "[::]:443"
tls.implicit = true
[server.listener.imap]
bind = "[::]:143"
protocol = "imap"
[server.listener.imaptls]
bind = "[::]:993"
protocol = "imap"
tls.implicit = true
[server.listener.sieve]
bind = "[::]:4190"
protocol = "managesieve"
[server.listener.smtp]
bind = "[::]:25"
protocol = "smtp"
greeting = "Lama Corp. ESMTL at your service"
[server.listener.submission]
bind = "[::]:587"
protocol = "smtp"
greeting = "Lama Corp. ESMTL at your service"
[server.listener.submissions]
bind = "[::]:465"
protocol = "smtp"
greeting = "Lama Corp. ESMTL at your service"
tls.implicit = true

[acme.letsencrypt-lama-corp-space]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = [
  "autoconfig.lama-corp.space",
  "autodiscover.lama-corp.space",
  "mail.lama-corp.space",
  "mta-sts.lama-corp.space",
]
cache = "/opt/stalwart/etc/acme"
default = true

[acme.letsencrypt-as212024-net]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.as212024.net", "mta-sts.as212024.net"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-lama-tel]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.lama.tel", "mta-sts.lama.tel"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-marcerisson-space]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.marcerisson.space", "mta-sts.marcerisson.space"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-risson-me]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.risson.me", "mta-sts.risson.me"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-risson-net]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.risson.net", "mta-sts.risson.net"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-risson-space]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.risson.space", "mta-sts.risson.space"]
cache = "/opt/stalwart/etc/acme"
default = false
[acme.letsencrypt-thefractal-space]
directory = "https://acme-v02.api.letsencrypt.org/directory"
challenge = "tls-alpn-01"
contact = ["root@lama-corp.space"]
domains = ["mail.thefractal.space", "mta-sts.thefractal.space"]
cache = "/opt/stalwart/etc/acme"
default = false

[http]
hsts = true
permissive-cors = true

[storage]
data = "postgresql"
blob = "postgresql"
fts = "postgresql"
lookup = "redis"
directory = "postgresql-authentik"

[storage.full-text]
default-language = "en"

[store.postgresql]
type = "postgresql"
host = "postgresql.fsn.as212024.net"
database = "stalwart"
user = "%{file:/postgres-creds/username}%"
password = "%{file:/postgres-creds/password}%"
compression = "none"
[store.postgresql.tls]
enable = false
allow-invalid-certs = true
[store.postgresql.purge]
frequency = "0 1 *"

[store.postgresql-authentik]
type = "postgresql"
host = "postgresql.fsn.as212024.net"
database = "authentik"
user = "%{file:/postgres-creds/username}%"
password = "%{file:/postgres-creds/password}%"
compression = "none"
[store.postgresql-authentik.tls]
enable = false
allow-invalid-certs = true
[store.postgresql-authentik.query]
name = "%{file:/config/name.sql}%"
members = "%{file:/config/members.sql}%"
recipients = "%{file:/config/recipients.sql}%"
emails = "%{file:/config/emails.sql}%"

[store.redis]
type = "redis"
redis-type = "single"
urls = "redis://redis.fsn.as212024.net:6379#insecure"
compression = "none"
[store.redis.purge]
frequency = "0 1 *"

[directory.postgresql-authentik]
type = "sql"
store = "postgresql-authentik"
[directory.postgresql-authentik.columns]
name = "name"
description = "description"
secret = "secret"
email = "address"
quota = "quota"
class = "type"

[email.encryption]
enable = false

[session.extensions]
no-soliciting = "'abcdefu'"
[session.rcpt]
sub-addressing = true
catch-all = true
[session.mta-sts]
mode = "testing"
max-age = "7d"

[auth.iprev]
verify = [{ if = "local_port == 25", then = "strict" }, { else = "disable" }]

[queue.outbound]
ip-strategy = "ipv4_only"
[queue.outbound.tls]
allow-invalid-certs = [
  { if = "retry_num > 0 && last_error == 'tls'", then = true },
  { else = false },
]
starttls = [
  { if = "retry_num > 1 && last_error == 'tls'", then = "disable" },
  { else = "require" },
]

[spam-filter]
auto-update = true

[resolver]
custom = ["[2001:67c:17fc:ffff::1]", "209.112.97.241"]

[report]
domain = "lama-corp.space"
[report.analysis]
addresses = ["dmarc@*", "abuse@*", "postmaster@*"]
forward = true
store = "365d"

[tracer.log]
type = "console"
level = "debug"
ansi = true
enable = true

[metrics.prometheus]
enable = true

[authentication.fallback-admin]
user = "admin"
secret = "%{file:/secrets/fallback-admin_secret}%"

[authentication.master]
user = "master"
secret = "%{file:/secrets/master_secret}%"
