---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-observability-grafana
  labels:
    app: infra-observability
spec:
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: infra-observability
  sources:
    - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
      targetRevision: HEAD
      path: k8s/infra/observability/grafana
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 10.5.12
      chart: grafana
      helm:
        releaseName: grafana
        values: |
          replicas: 1
          grafana.ini:
            analytics:
              reporting_enabled: "False"
              check_for_updates: "False"
            features_toggles:
              enable: dashboardPreviews scenes
            server:
              domain: grafana.as212024.net
              enforce_domain: "True"
              root_url: https://grafana.as212024.net
            security:
              disable_initial_admin_creation: "True"
              cookie_secure: "True"
            auth:
              signout_redirect_url: https://auth.as212024.net/application/o/grafana/end-session/
            auth.anonymous:
              enabled: "True"
              org_name: "Main Org."
            auth.generic_oauth:
              name: authentik
              enabled: "True"
              allow_sign_up: "True"
              scopes: "openid email profile"
              auth_url: https://auth.as212024.net/application/o/authorize/
              token_url: https://auth.as212024.net/application/o/token/
              api_url: https://auth.as212024.net/application/o/userinfo/
              role_attribute_path: "contains(groups[*], 'roots') && 'Admin' || 'Viewer'"
              allow_assign_grafana_admin: "True"
              role_attribute_strict: "True"
              use_pkce: "True"
            users:
              auto_assign_org: "True"
              auto_assign_org_id: 1
            database:
              type: postgres
              host: postgresql.fsn.as212024.net
              name: grafana
              ssl_mode: require
          envValueFrom:
            GF_DATABASE_USER:
              secretKeyRef:
                name: grafana-postgres-credentials
                key: username
            GF_DATABASE_PASSWORD:
              secretKeyRef:
                name: grafana-postgres-credentials
                key: password
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
              secretKeyRef:
                name: grafana-oidc-credentials
                key: client_id
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-oidc-credentials
                key: client_secret

          annotations:
            secret.reloader.stakater.com/reload: grafana-postgres-credentials,grafana-oidc-credentials

          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
                - name: VMetrics
                  type: victoriametrics-metrics-datasource
                  access: proxy
                  url: http://vmsingle-vm.infra-observability:8429/
                  isDefault: true
                - name: VProm
                  type: prometheus
                  access: proxy
                  url: http://vmsingle-vm.infra-observability:8429/
                  editable: false
                - name: VLogs
                  type: victoriametrics-logs-datasource
                  access: proxy
                  url: http://vlsingle-vm.infra-observability:9428/
                  editable: false

          sidecar:
            dashboards:
              enabled: true
              labelValue: "1"
              folderAnnotation: k8s-sidecar-target-directory
              searchNamespace: ALL
              provider:
                foldersFromFilesStructure: true
              multicluster:
                global:
                  enabled: true
                etcd:
                  enabled: true
            datasources:
              enabled: true
              labelValue: "1"

          plugins:
            - grafana-polystat-panel
            - grafana-worldmap-panel
            - marcusolsson-treemap-panel
            - victoriametrics-metrics-datasource
            - victoriametrics-logs-datasource

          route:
            main:
              enabled: true
              parentRefs:
                - name: eg-http-public
                  namespace: core-eg
                  sectionName: https
              hostnames:
                - grafana.as212024.net
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: grafana
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
    - group: ""
      kind: Secret
      name: grafana
      jsonPointers:
        - /data/admin-password
