---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: archivebox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: archive.lama-corp.space
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: archivebox-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: archivebox
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: archivebox
  hostnames:
    - archive.lama-corp.space
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: archivebox
          port: 80
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: archivebox
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: archivebox
  oidc:
    provider:
      issuer: https://auth.lama-corp.space/application/o/archivebox/
    clientID: archivebox
    clientSecret:
      name: archivebox-oidc-credentials
    scopes:
      - offline_access
      - profile
    refreshToken: true
    forwardAccessToken: true
    passThroughAuthHeader: true
  jwt:
    providers:
      - name: authentik
        issuer: https://auth.lama-corp.space/application/o/archivebox/
        remoteJWKS:
          uri: https://auth.lama-corp.space/application/o/archivebox/jwks/
        claimToHeaders:
          - header: "X-Remote-User"
            claim: preferred_username
