---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-authentik
spec:
  provider:
    vault:
      server: https://vault.as212024.net
      path: authentik
      auth:
        kubernetes:
          mountPath: k8s-k3s.fsn.as212024.net
          role: common
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-oidc-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-authentik
  dataFrom:
    - extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-archivebox
      rewrite:
        - regexp:
            source: client_secret
            target: client-secret
