---
apiVersion: cilium.io/v2
kind: CiliumEgressGatewayPolicy
metadata:
  name: services-media-download-egress
spec:
  selectors:
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: services-media
          app.kubernetes.io/name: media
          app.kubernetes.io/component: flaresolverr
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: services-media
          app.kubernetes.io/name: media
          app.kubernetes.io/component: jackett
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: services-media
          app.kubernetes.io/name: media
          app.kubernetes.io/component: prowlarr
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: services-media
          app.kubernetes.io/name: media
          app.kubernetes.io/component: qbittorrent
    - podSelector:
        matchLabels:
          io.kubernetes.pod.namespace: services-media
          app.kubernetes.io/name: media
          app.kubernetes.io/component: sabnzbd
  destinationCIDRs:
    - "0.0.0.0/0"
  egressGateway:
    nodeSelector:
      matchLabels:
        kubernetes.io/hostname: k3s-2.bar.as212024.net
    egressIP: 172.29.2.12
