---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: hetzner-extra-subnet-1
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: 148.251.148.234/32
    - cidr: 148.251.148.235/32
    - cidr: 148.251.148.236/32
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: as212024-pi
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - cidr: 209.112.97.53/32
    - cidr: 209.112.97.160/28
    - cidr: 2001:67c:17fc::/64
    - cidr: 2001:67c:17fc:130::/60
