---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-authentik
  labels:
    app: services-authentik
spec:
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: services-authentik
  sources:
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      ref: infrastructure
    - repoURL: https://charts.goauthentik.io
      targetRevision: 2026.5.3
      chart: authentik
      helm:
        releaseName: authentik
        valueFiles:
          - $infrastructure/k8s/services/authentik/values.yml
    - repoURL: https://github.com/LamaCorp/infrastructure.git
      targetRevision: HEAD
      path: k8s/services/authentik/extra
