---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-lemmy
  labels:
    app: services-lemmy
spec:
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: services-lemmy
  source:
    repoURL: https://github.com/LamaCorp/infrastructure.git
    targetRevision: HEAD
    path: k8s/services/lemmy/app
