---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: paperless-ngx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: paper.risson.space
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: paperless-ngx-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paperless-ngx
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: paperless-ngx
  hostnames:
    - paper.risson.space
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: paperless-ngx
          port: 80
