---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-media-repo-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-matrix_media-repo
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-repo-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          repo:
            bindAddress: ""
            port: 8000
            logDirectory: "-"
            trustAnyForwardedAddress: true
            useForwardedHost: false
            logLevel: trace
          metrics:
            enabled: true
            bindAddress: ""
            port: 9000
          database:
            postgres: "postgres://{{ .username }}:{{ .password }}@postgresql.fsn.as212024.net:6432/matrix_media_repo?sslmode=require"
          homeservers:
            - name: lama-corp.space
              csApi: https://matrix.lama-corp.space/
              adminApiKind: synapse
          admins:
            - "@risson:lama-corp.space"
          datastores:
            - type: s3
              id: s3.lama-corp.space
              forKinds:
                - all
              opts:
                tempPath: /tmp/media_repo_s3_upload
                endpoint: s3.lama-corp.space
                accessKeyId: "{{ .access_key }}"
                accessSecret: "{{ .secret_key }}"
                ssl: true
                bucketName: matrix-media
          uploads:
            maxBytes: 104857600 # 100MB
            maxPending: 50
            maxAgeSeconds: 86400 # 24h
            quotas:
              enabled: true
              users:
                - glob: "@*:*"
                  maxBytes: 10737418240 # 10GB
                - glob: "@*:lama-corp.space"
                  maxBytes: 21474836480 # 20GB
          urlPreviews:
            disallowedNetworks:
              - "127.0.0.0/8"
              - "10.0.0.0/8"
              - "172.16.0.0/12"
              - "192.168.0.0/16"
              - "100.64.0.0/10"
              - "192.0.0.0/24"
              - "169.254.0.0/16"
              - "192.88.99.0/24"
              - "198.18.0.0/15"
              - "192.0.2.0/24"
              - "198.51.100.0/24"
              - "203.0.113.0/24"
              - "224.0.0.0/4"
              - "::1/128"
              - "fe80::/10"
              - "fc00::/7"
              - "2001:db8::/32"
              - "ff00::/8"
              - "fec0::/10"
              - "2001:67c:17fc:110::/60"
              - "2001:67c:17fc:120::/60"
            allowedNetworks:
              - "0.0.0.0/0"
              - "::/0"
            expireAfterDays: 30
            defaultLanguage: "fr-FR,fr,en-US,en-GB,en"
            oEmbed: true
          thumbnails:
            expireAfterDays: 30
  dataFrom:
    - extract:
        key: /services-matrix/s3-matrix
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-media-repo-postgres-credentials
