---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mastodon
spec:
  schedule: "49 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mastodon
              args:
                - |
                  bin/tootctl media remove --days=7 --prune-profiles --include-follows
                  bin/tootctl preview_cards remove --days=15
