---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-rocketchat-mongodb-credentials
spec:
  path: /mongodb/creds/mongodb.fsn.as212024.net_k3s.fsn.as212024.net_services-rocketchat-lama
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocketchat-mongodb-credentials
spec:
  refreshInterval: 20d
  target:
    template:
      engineVersion: v2
      data:
        mongo-uri: "mongodb://{{ .username }}:{{ .password }}@mongodb.fsn.as212024.net/rocketchatLama"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-rocketchat-mongodb-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocketchat-smtp-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-rocketchat-lama/aws-ses-rocketchat-lama
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocketchat-oidc-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-authentik
  dataFrom:
    - extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-rocketchat-lama
