---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-synapse-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-matrix_synapse
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-postgres-credentials
spec:
  refreshInterval: 1m
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-synapse-postgres-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-signing-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-matrix/synapse/signing-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          macaroon_secret_key: "{{ .macaroon_secret_key }}"
          form_secret: "{{ .form_secret }}"
          oidc_providers:
            - idp_id: authentik
              idp_name: Lama Corp. Connect
              issuer: https://auth.lama-corp.space/application/o/matrix/
              client_id: "{{ .client_id }}"
              client_secret: "{{ .client_secret }}"
              pkce_method: always
              scopes:
                - openid
                - profile
                - email
              allow_existing_users: true
              enable_registration: true
              user_mapping_provider:
                config:
                  subject_template: "{{ `{{ user.sub }}` }}"
                  picture_template: "{{ `{{ user.avatar }}` }}"
                  localpart_template: "{{ `{{ user.preferred_username }}` }}"
                  confirm_localpart: false
                  display_name_template: "{{ `{{ user.name }}` }}"
                  email_template: "{{ `{{ user.email }}` }}"
          modules:
            - module: shared_secret_authenticator.SharedSecretAuthProvider
              config:
                shared_secret: "{{ .auth_shared_secret }}"
                m_login_password_support_enabled: true
                com_devture_shared_secret_auth_support_enabled: false
          email:
            app_name: Matrix - Lama Corp.
            client_base_url: https://element.lama-corp.space
            enable_notifs: true
            enable_tls: true
            invite_client_location: https://element.lama-corp.space
            notif_for_new_users: true
            notif_from: "Matrix - Lama Corp. <no-reply-matrix@lama-corp.space>"
            require_transport_security: true
            smtp_host: email-smtp.eu-west-3.amazonaws.com
            smtp_port: 587
            smtp_user: "{{ .username }}"
            smtp_pass: "{{ .password }}"
  dataFrom:
    - extract:
        key: /services-matrix/synapse/secrets
    - extract:
        key: /services-matrix/aws-ses-matrix
    - sourceRef:
        storeRef:
          kind: SecretStore
          name: vault-authentik
      extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-matrix/synapse
