---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: authentik-rs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: as212024.net
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: authentik-rs-https
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-rs
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: authentik-rs
  hostnames:
    - authentik.rs
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: goauthentik.io
            statusCode: 302
