---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  labels:
    app: apps
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/LamaCorp/infrastructure.git
        revision: HEAD
        files:
          - path: k8s/core/**/config.json
          - path: k8s/infra/**/config.json
          - path: k8s/services/**/config.json
  template:
    metadata:
      name: apps-{{ normalize (index .path.segments 1) }}-{{ normalize (index .path.segments 2) }}
      labels:
        app: apps
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
      destination:
        name: k3s.fsn.as212024.net
        namespace: argocd
      source:
        repoURL: https://github.com/LamaCorp/infrastructure.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
