---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    app: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: k3s.fsn.as212024.net
    namespace: argocd
  sources:
    - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
      targetRevision: HEAD
      ref: infrastructure
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.1.4
      helm:
        releaseName: argocd
        valueFiles:
          - $infrastructure/k8s/argocd/values.yml
    - repoURL: https://gitlab.com/lama-corp/infra/infrastructure.git
      targetRevision: HEAD
      path: k8s/argocd
