---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: media

resources:
  - network-policy.yml
  - pvc.yml
  - secrets.yml

  - bazarr
  - flaresolverr
  - jackett
  - jellyfin
  - jellyseerr
  - lidarr
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - recyclarr
  - sabnzbd
  - sonarr

configMapGenerator:
  - name: media-config-env
    literals:
      - PUID=10095
      - PGID=10095
      - UMASK=002
      - TZ=Europe/Paris

images:
  - name: ghcr.io/hotio/bazarr
    newTag: release-1.5.2
  - name: ghcr.io/flaresolverr/flaresolverr
    newTag: v3.4.6
  - name: ghcr.io/hotio/jackett
    newTag: release-0.22.2374
  - name: ghcr.io/jellyfin/jellyfin
    newTag: 10.11.5
  - name: ghcr.io/hotio/jellyseerr
    newName: fallenbagel/jellyseerr
    newTag: preview-OIDC
  - name: ghcr.io/hotio/lidarr
    newTag: release-2.13.3.4711
  - name: ghcr.io/hotio/prowlarr
    newTag: release-2.0.5.5160
  - name: ghcr.io/hotio/qbittorrent
    newTag: release-5.1.2
  - name: ghcr.io/hotio/radarr
    newTag: release-5.26.2.10099
  - name: ghcr.io/hotio/readarr
    newTag: testing-0.3.32.2587
  - name: ghcr.io/recyclarr/recyclarr
    newTag: 7.5.2
  - name: ghcr.io/hotio/sabnzbd
    newTag: release-4.5.3
  - name: ghcr.io/hotio/sonarr
    newTag: release-4.0.15.2941
  - name: ghcr.io/qdm12/gluetun
    newTag: v3.40.0
