---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: gatus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg-http-public
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: gatus
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: gatus-tls
