---
postgresql_version: 17

postgresql_users:
  postgres:
    password: "{{ lookup('community.hashi_vault.hashi_vault', 'databases/data/postgres/postgresql.fsn.as212024.net/postgres')['password'] }}"

  atuin: {}
  authentik: {}
  gatus_devoups: {}
  gatus_phowork: {}
  gatus_prologin: {}
  gatus_zarak: {}
  grafana: {}
  hedgedoc: {}
  immich: {}
  lemmy: {}
  lemmy_pictrs: {}
  mastodon: {}
  matrix_maubot: {}
  matrix_mautrix_facebook: {}
  matrix_mautrix_slack: {}
  matrix_media_repo: {}
  matrix_synapse: {}
  mattermost: {}
  netbox: {}
  nextcloud: {}
  paperless_risson: {}

postgresql_dbs:
  atuin: atuin
  authentik: authentik
  gatus_devoups: gatus_devoups
  gatus_phowork: gatus_phowork
  gatus_prologin: gatus_prologin
  gatus_zarak: gatus_zarak
  grafana: grafana
  hedgedoc: hedgedoc
  immich: immich
  lemmy: lemmy
  lemmy_pictrs: lemmy_pictrs
  mailman: postgres
  mastodon: mastodon
  matrix_maubot: matrix_maubot
  matrix_mautrix_facebook: matrix_mautrix_facebook
  matrix_mautrix_slack: matrix_mautrix_slack
  matrix_media_repo: matrix_media_repo
  matrix_synapse: matrix_synapse
  mattermost: mattermost
  netbox: netbox
  nextcloud: nextcloud
  paperless_risson: paperless_risson

postgresql_config:
  ssl_cert_file: "'/srv/acme/postgresql.fsn.as212024.net/fullchain.pem'"
  ssl_key_file: "'/srv/acme/postgresql.fsn.as212024.net/key.pem'"

  # See https://pgtune.leopard.in.ua/
  # and https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
  max_connections: 500
  shared_buffers: 4GB
  effective_cache_size: 12GB
  maintenance_work_mem: 819MB
  checkpoint_completion_target: 0.9
  wal_buffers: -1
  default_statistics_target: 100
  random_page_cost: 1.1
  effective_io_concurrency: 200
  work_mem: 8MB
  min_wal_size: 2GB
  max_wal_size: 3GB
  max_worker_processes: 8
  max_parallel_workers_per_gather: 4
  max_parallel_workers: 8
  max_parallel_maintenance_workers: 4

postgresql_authentication_policies:
  - type: host
    database: all
    user: all
    address: "172.28.0.0/16"
    method: scram-sha-256
  - type: host
    database: all
    user: all
    address: "2001:67c:17fc::/48"
    method: scram-sha-256
