---
apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: vm
spec:
  replicaCount: 1
  retentionPeriod: "5y"
  useStrictSecurity: true
  extraArgs:
    enableTCP6: "true"
  resources:
    requests:
      cpu: 150m
      memory: 4Gi
    limits:
      memory: 4Gi
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  nodeSelector:
    k8s.as212024.net/role: storage
  tolerations:
    - key: k8s.as212024.net/role
      operator: Equal
      value: storage
      effect: NoExecute
---
apiVersion: v1
kind: Service
metadata:
  name: vlsingle-vm-lb
  annotations:
    io.cilium/lb-ipam-ips: 209.112.97.166,2001:67c:17fc:130::9428
    external-dns.alpha.kubernetes.io/hostname: vlogs.as212024.net
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  ports:
    - name: http
      port: 9428
      targetPort: 9428
      protocol: TCP
  selector:
    app.kubernetes.io/name: vlsingle
    app.kubernetes.io/instance: vm
