---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-external-secrets
  labels:
    app: core-external-secrets
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: core-external-secrets-{{ .name }}
      labels:
        app: core-external-secrets
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
      destination:
        name: "{{ .name }}"
        namespace: core-external-secrets
      sources:
        - repoURL: https://github.com/LamaCorp/infrastructure.git
          targetRevision: HEAD
          path: k8s/core/external-secrets/extra/{{ .name }}
        - repoURL: https://charts.external-secrets.io
          targetRevision: 2.4.0
          chart: external-secrets
          helm:
            releaseName: external-secrets
            values: |
              serviceMonitor:
                enabled: true
              webhook:
                serviceMonitor:
                  enabled: true
              certController:
                serviceMonitor:
                  enabled: true
