---
bird_router_id: 209.112.97.241

bird_bgp_preferred_source:
  v4: 209.112.97.241
  v6: 2001:67c:17fc:ffff::1

bird_static_routes:
  v4:
    - 148.251.148.232/29 unreachable
    - 209.112.97.232/32 unreachable # nat-svc
    - 209.112.97.233/32 unreachable # nat-mdw
    - 209.112.97.234/32 unreachable # nat-cust
  v6:
    - 2001:67c:17fc::25/128 unreachable # mail.as212024.net

bird_bgp_sessions:
  cores:
    defaults:
      local:
        v4: 209.112.97.241
        v6: 2001:67c:17fc:ffff::1
      med_metric: true
    sessions:
      - description: BAR
        alias: bar
        asn: 212024
        remote:
          v4: 209.112.97.242
          v6: 2001:67c:17fc:ffff::2
      - description: PVL
        alias: pvl
        asn: 212024
        remote:
          v4: 209.112.97.243
          v6: 2001:67c:17fc:ffff::3
      - description: FRA
        alias: fra
        asn: 212024
        remote:
          v4: 209.112.97.244
          v6: 2001:67c:17fc:ffff::4

bird_ospf_sessions:
  - alias: ospf
    export_static_routes: true
    areas:
      0.0.0.0:
        interfaces:
          zt-lama:
            cost: 20
          br-svc:
            cost: 1
          br-mdw:
            stub: true
          br-cc:
            stub: true
