---
nft_define_host:
  bgp interfaces:
    name: bgp_interfaces
    value: "{zt-lama, core-bar-4, core-bar-6, core-pvl-4, core-pvl-6, core-fra-4, core-fra-6}"
  ospf interfaces:
    name: ospf_interfaces
    value: "{zt-lama, lan-svc-101, core-bar-4, core-bar-6, core-pvl-4, core-pvl-6, core-fra-4, core-fra-6}"

nft_input_host_rules:
  500 k3s api:
    - tcp dport 6443 accept

nft__nat_host_postrouting_rules:
  100 external connectivity:
    - meta oif ul-hetzner-0 ip saddr 172.28.0.0/16 ip saddr != {136.243.102.29, 148.251.148.232/29} counter snat to 148.251.148.239
    - meta oif ul-hetzner-0 ip saddr != {136.243.102.29, 148.251.148.232/29} counter snat to 136.243.102.29
    - meta iif lan-svc-101 oifname zt-lama ip saddr != 209.112.97.0/24 ip daddr != {209.112.97.0/24, 172.28.0.0/16, 172.29.0.0/16} counter snat to 209.112.97.232
    - meta iif lan-mdw-102 oifname zt-lama ip saddr != 209.112.97.0/24 ip daddr != {209.112.97.0/24, 172.28.0.0/16, 172.29.0.0/16} counter snat to 209.112.97.233
    - meta iif cl-vm-0 oifname zt-lama ip saddr != 209.112.97.0/24 ip daddr != {209.112.97.0/24, 172.28.0.0/16, 172.29.0.0/16} counter snat to 209.112.97.234
    # TODO: drop these
    - meta oifname zt-lama ip saddr != 209.112.97.0/24 ip daddr != {209.112.97.0/24, 172.28.0.0/16, 172.29.0.0/16} counter masquerade
