---
network_nameservers:
  - ::1
  - 127.0.0.1

netplan_configuration:
  network:
    version: 2
    ethernets:
      enp7s0:
        accept-ra: true
        addresses:
          - 136.243.102.29/32
          - 2a01:4f8:171:b0d::1/128
          - 2a01:4f8:171:b0d::2/64
        routes:
          - to: 0.0.0.0/0
            via: 136.243.102.1
            on-link: true
          - to: 0.0.0.0/0
            via: 136.243.102.1
            on-link: true
            table: 101
          - to: ::/0
            via: fe80::1
          - to: ::/0
            via: fe80::1
            table: 101
          - to: 148.251.148.232/29
            via: 0.0.0.0
            type: unreachable
        routing-policy:
          - from: 2a01:4f8:171:b0d::/64
            table: 101
          - from: 136.243.102.29/32
            table: 101
          - from: 148.251.148.232/29
            table: 101
    bridges:
      br-svc:
        mtu: 5600
        addresses:
          - 172.28.1.62/26
          - 2001:67c:17fc:101::1/64
        routes:
          - to: 209.112.97.232/32 # nat-svc
            via: 0.0.0.0
            type: unreachable
      br-mdw:
        mtu: 5600
        addresses:
          - 172.28.1.126/26
          - 2001:67c:17fc:102::1/64
        routes:
          - to: 148.251.148.232/32 # mail.as212024.net
            via: 172.28.1.90 # mail.fsn.as212024.net
          - to: 2001:67c:17fc::25/128 # mail.as212024.net
            via: 2001:67c:17fc:102::90 # mail.fsn.as212024.net
          - to: 209.112.97.233/32 # nat-mdw
            via: 0.0.0.0
            type: unreachable
      br-cc:
        mtu: 1500
        addresses:
          - 172.29.1.62/26
          - 2a06:e881:7701:1::1/64
        routes:
          - to: 148.251.148.233/32 # pine.lama-corp.space
            via: 172.29.1.20 # pine.fsn.as212024.net
          - to: 209.112.97.234/32 # nat-cust
            via: 0.0.0.0
            type: unreachable
