---
systemd_networkd_link:
  # Hetzner uplink
  10-ul-hetzner-0:
    Match:
      MACAddress: 50:eb:f6:ba:2d:da
    Link:
      Name: ul-hetzner-0

systemd_networkd_netdev:
  # core VPN
  15-core-bar-4:
    NetDev:
      Name: core-bar-4
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51842
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/gate-1.bar.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
  15-core-bar-6:
    NetDev:
      Name: core-bar-6
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51862
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/gate-1.bar.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
  15-core-pvl-4:
    NetDev:
      Name: core-pvl-4
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51843
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-1.pvl.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: 108.61.208.236:51841
  15-core-pvl-6:
    NetDev:
      Name: core-pvl-6
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51863
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-1.pvl.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb]:51861"
  15-core-fra-4:
    NetDev:
      Name: core-fra-4
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51844
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-2.fra.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: 194.50.92.165:51841
  15-core-fra-6:
    NetDev:
      Name: core-fra-6
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51864
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-2.fra.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a09:4c0:303:c232::5ca5]:51841"
  # service VMs like k8s
  20-lan-svc-101:
    NetDev:
      Name: lan-svc-101
      Kind: bridge
      MTUBytes: 9000
  # middlewares: postgres, redis, mongo, mail, etc.
  20-lan-mdw-102:
    NetDev:
      Name: lan-mdw-102
      Kind: bridge
      MTUBytes: 9000
  # client VMs
  30-cl-vm-0:
    NetDev:
      Name: cl-vm-0
      Kind: bridge
      MTUBytes: 1500

systemd_networkd_network:
  # Hetzner uplink
  10-ul-hetzner-0:
    Match:
      Name: ul-hetzner-0
    Link:
      RequiredForOnline: true
    Network:
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: true
      Address:
        - 136.243.102.29/32
        - 2a01:4f8:171:b0d::1/128
        - 2a01:4f8:171:b0d::2/64
    Route:
      # Hetzner default routes
      - Destination: 0.0.0.0/0
        Gateway: 136.243.102.1
        GatewayOnLink: true
      - Destination: ::/0
        Gateway: fe80::1
      - Destination: 0.0.0.0/0
        Gateway: 136.243.102.1
        GatewayOnLink: true
        Table: 101
      - Destination: ::/0
        Gateway: fe80::1
        Table: 101
      # Hetzner /29 blackholed, more specific routes exist
      - Destination: 148.251.148.232/29
        Gateway: 0.0.0.0
        Type: unreachable
    RoutingPolicyRule:
      # from Hetzner IPs
      - From: 136.243.102.29/32
        Table: 101
      - From: 2a01:4f8:171:b0d::/64
        Table: 101
      # from Hetzner /29
      - From: 148.251.148.232/29
        Table: 101
      # core VPN
      - To: 108.61.208.236/32
        Table: 101
      - To: 2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb/128
        Table: 101
      - To: 194.50.92.165/32
        Table: 101
      - To: 2a09:4c0:303:c232::5ca5/128
        Table: 101
  # core VPN
  15-core-bar-4:
    Match:
      Name: core-bar-4
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.4.1/24
        - fe80::4:1/64
  15-core-bar-6:
    Match:
      Name: core-bar-6
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.6.1/24
        - fe80::6:1/64
  15-core-pvl-4:
    Match:
      Name: core-pvl-4
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.4.1/24
        - fe80::4:1/64
  15-core-pvl-6:
    Match:
      Name: core-pvl-6
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.6.1/24
        - fe80::6:1/64
  15-core-fra-4:
    Match:
      Name: core-fra-4
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.4.1/24
        - fe80::4:1/64
  15-core-fra-6:
    Match:
      Name: core-fra-6
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.6.1/24
        - fe80::6:1/64
  # service VMs like k8s
  20-lan-svc-101:
    Match:
      Name: lan-svc-101
    Link:
      RequiredForOnline: false
      MTUBytes: 9000
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.1.62/26
        - 2001:67c:17fc:101::1/64
    Route:
      - Destination: 209.112.97.232/32 # nat-svc
        Gateway: 0.0.0.0
        Type: unreachable
  # middlewares: postgres, redis, mongo, mail, etc.
  20-lan-mdw-102:
    Match:
      Name: lan-mdw-102
    Link:
      RequiredForOnline: false
      MTUBytes: 9000
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.1.126/26
        - 2001:67c:17fc:102::1/64
    Route:
      - Destination: 148.251.148.232/32 # mail.as212024.net
        Gateway: 172.28.1.90 # mail.fsn.as212024.net
      - Destination: 2001:67c:17fc::25/128 # mail.as212024.net
        Gateway: 2001:67c:17fc:102::90 # mail.fsn.as212024.net
      - Destination: 209.112.97.233/32 # nat-mdw
        Gateway: 0.0.0.0
        Type: unreachable
  # client VMs
  30-cl-vm-0:
    Match:
      Name: cl-vm-0
    Link:
      RequiredForOnline: false
      MTUBytes: 1500
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.1.62/26
        - 2a06:e881:7701:1::1/64
    Route:
      - Destination: 148.251.148.233/32 # pine.lama-corp.space
        Gateway: 172.29.1.20 # pine.fsn.as212024.net
      - Destination: 209.112.97.234/32 # nat-cust
        Gateway: 0.0.0.0
        Type: unreachable
