---
systemd_networkd_link:
  # Hetzner uplink
  10-ul-hetzner-0:
    Match:
      MACAddress: 50:eb:f6:ba:2d:da
    Link:
      Name: ul-hetzner-0

systemd_networkd_netdev:
  10-id:
    NetDev:
      Name: id
      Kind: dummy
  # core VPN
  15-core-bar:
    NetDev:
      Name: core-bar
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51802
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/gate-1.bar.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
  15-core-pvl:
    NetDev:
      Name: core-pvl
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51803
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-1.pvl.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb]:51801"
  15-core-fra:
    NetDev:
      Name: core-fra
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51804
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-2.fra.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a09:4c0:303:c232::5ca5]:51801"
  # service VMs like k8s
  20-lan-svc-101:
    NetDev:
      Name: lan-svc-101
      Kind: bridge
      MTUBytes: 1420
  # middlewares: postgres, redis, mongo, mail, etc.
  20-lan-mdw-102:
    NetDev:
      Name: lan-mdw-102
      Kind: bridge
      MTUBytes: 1420
  # client VMs
  30-cl-vm-0:
    NetDev:
      Name: cl-vm-0
      Kind: bridge
      MTUBytes: 1420

systemd_networkd_network:
  10-id:
    Match:
      Name: id
    Link:
      RequiredForOnline: true
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 209.112.97.241/32
        - 2001:67c:17fc:ffff::1/128
  # Hetzner uplink
  10-ul-hetzner-0:
    Match:
      Name: ul-hetzner-0
    Link:
      RequiredForOnline: true
    Network:
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: true
      Address:
        - 136.243.102.29/32
        - 2a01:4f8:171:b0d::1/128
        - 2a01:4f8:171:b0d::2/64
    Route:
      # Hetzner default routes
      - Destination: 0.0.0.0/0
        Gateway: 136.243.102.1
        GatewayOnLink: true
      - Destination: ::/0
        Gateway: fe80::1
      - Destination: 0.0.0.0/0
        Gateway: 136.243.102.1
        GatewayOnLink: true
        Table: 101
      - Destination: ::/0
        Gateway: fe80::1
        Table: 101
      # Hetzner /29 blackholed, more specific routes exist
      - Destination: 148.251.148.232/29
        Gateway: 0.0.0.0
        Type: unreachable
    RoutingPolicyRule:
      # from Hetzner IPs
      - From: 136.243.102.29/32
        Table: 101
      - From: 2a01:4f8:171:b0d::/64
        Table: 101
      # from Hetzner /29
      - From: 148.251.148.232/29
        Table: 101
      # core VPN
      - To: 108.61.208.236/32
        Table: 101
      - To: 2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb/128
        Table: 101
      - To: 194.50.92.165/32
        Table: 101
      - To: 2a09:4c0:303:c232::5ca5/128
        Table: 101
  # core VPN
  15-core-bar:
    Match:
      Name: core-bar
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.0/31
        - fe80::0:0/127
  15-core-pvl:
    Match:
      Name: core-pvl
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.2/31
        - fe80::0:2/127
  15-core-fra:
    Match:
      Name: core-fra
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.4/31
        - fe80::0:4/127
  # service VMs like k8s
  20-lan-svc-101:
    Match:
      Name: lan-svc-101
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.1.62/26
        - 2001:67c:17fc:101::1/64
    Route:
      - Destination: 209.112.97.232/32 # nat-svc
        Gateway: 0.0.0.0
        Type: unreachable
  # middlewares: postgres, redis, mongo, mail, etc.
  20-lan-mdw-102:
    Match:
      Name: lan-mdw-102
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.28.1.126/26
        - 2001:67c:17fc:102::1/64
    Route:
      - Destination: 148.251.148.232/32 # mail.as212024.net
        Gateway: 172.28.1.90 # mail.fsn.as212024.net
      - Destination: 2001:67c:17fc::25/128 # mail.as212024.net
        Gateway: 2001:67c:17fc:102::90 # mail.fsn.as212024.net
      - Destination: 209.112.97.233/32 # nat-mdw
        Gateway: 0.0.0.0
        Type: unreachable
  # client VMs
  30-cl-vm-0:
    Match:
      Name: cl-vm-0
    Link:
      RequiredForOnline: false
    Network:
      ConfigureWithoutCarrier: true
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: false
      Address:
        - 172.29.1.62/26
        - 2a06:e881:7701:1::1/64
    Route:
      - Destination: 148.251.148.233/32 # pine.lama-corp.space
        Gateway: 172.29.1.20 # pine.fsn.as212024.net
      - Destination: 209.112.97.234/32 # nat-cust
        Gateway: 0.0.0.0
        Type: unreachable
