#!/usr/bin/env ansible-playbook
---
- name: Base
  import_playbook: ../base.yml

- name: Snapcast server
  hosts: snapserver
  roles:
    - snapcast
  tags:
    - apps
    - snapcast
    - snapserver

- name: Snapcast server
  hosts: snapclient
  roles:
    - snapcast
  tags:
    - apps
    - snapcast
    - snapclient
