---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: vaultwarden

resources:
  - deployment.yml
  - httproute.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml
  - service.yml

configMapGenerator:
  - name: vaultwarden-config
    literals:
      - "ROCKET_ADDRESS=::"
      - ROCKET_PORT=8000
      - ROCKET_WORKERS=10
      - DISABLE_ADMIN_TOKEN=false
      - DOMAIN=https://warden.lama-corp.space
      - EMERGENCY_ACCESS_ALLOWED=true
      - PUSH_ENABLED=true
      - PUSH_RELAY_URI=https://api.bitwarden.eu
      - PUSH_IDENTITY_URI=https://identity.bitwarden.eu
      - INVITATIONS_ALLOWED=true
      - INVITATION_ORG_NAME=Lama Corp.
      - ORG_CREATION_USERS=all
      - REQUIRE_DEVICE_EMAIL=true
      - SENDS_ALLOWED=true
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_DOMAIN_WHITELIST=lama-corp.space,risson.space,lewdax.space
      - SIGNUPS_VERIFY=true
      - SMTP_FROM=no-reply@warden.lama-corp.space
      - SMTP_FROM_NAME=Bitwarden - Lama Corp.
      - SMTP_HOST=email-smtp.eu-west-3.amazonaws.com
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls

images:
  - name: quay.io/vaultwarden/server
    newTag: 1.35.0
