---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-hedgedoc-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-hedgedoc
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgedoc-postgres-credentials
spec:
  refreshInterval: 1m
  target:
    template:
      engineVersion: v2
      data:
        CMD_DB_URL: "postgres://{{ .username }}:{{ .password }}@postgresql.fsn.as212024.net/hedgedoc?ssl=true"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-hedgedoc-postgres-credentials
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.as212024.net
      path: k8s-k3s.fsn.as212024.net
      auth:
        kubernetes:
          mountPath: k8s-k3s.fsn.as212024.net
          role: common
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-authentik
spec:
  provider:
    vault:
      server: https://vault.as212024.net
      path: authentik
      auth:
        kubernetes:
          mountPath: k8s-k3s.fsn.as212024.net
          role: common
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgedoc-secrets
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-hedgedoc/secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgedoc-oidc-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-authentik
  target:
    template:
      engineVersion: v2
      data:
        CMD_OAUTH2_CLIENT_ID: "{{ .client_id }}"
        CMD_OAUTH2_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: /providers/oauth2/k8s/k3s.fsn.as212024.net/services-hedgedoc
