---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: lemmy

resources:
  - network-policy.yml
  - secrets.yml
  - lemmy
  - pictrs
  - lemmy-ui
  - httproute.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lemmy-config
    files:
      - ./config/config.hjson
  - name: pictrs-config
    literals:
      - PICTRS__SERVER__ADDRESS=[::]:8080
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
      - PICTRS__REPO__TYPE=sled
  - name: lemmy-ui-config
    literals:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:80
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=lemmy.lama-corp.space
      - LEMMY_UI_HTTPS=true

images:
  - name: docker.io/dessalines/lemmy
    newTag: 0.19.17@sha256:ed103195e5c6b2504fc20a3b51654478de44395178a5ca1734b10c05f46366af
  - name: docker.io/dessalines/lemmy-ui
    newTag: 0.19.18@sha256:b9eeb08a36371fafbcd34bca7afc75e17ce8f99fa3ca149532e88b5c5d763939
  - name: docker.io/asonix/pictrs
    newTag: 0.5.23@sha256:85bb2303fefdc6b47c37ecad55a02810e6d118f8499f250f2d32ace1097a2bdc
