---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: lemmy

resources:
  - network-policy.yml
  - secrets.yml
  - lemmy
  - pictrs
  - lemmy-ui
  - httproute.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: lemmy-config
    files:
      - ./config/config.hjson
  - name: pictrs-config
    literals:
      - PICTRS__SERVER__ADDRESS=[::]:8080
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
      - PICTRS__REPO__TYPE=postgres
  - name: lemmy-ui-config
    literals:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:80
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=lemmy.lama-corp.space
      - LEMMY_UI_HTTPS=true

images:
  - name: docker.io/dessalines/lemmy
    newTag: 0.19.16@sha256:5c4375478b12b82a3a2a4a13070650c47b17a250a274b1ffd98afc2b420077be
  - name: docker.io/dessalines/lemmy-ui
    newTag: 0.19.16@sha256:f752761d86428c836f0f2d8b24eef9e3f7600e9dfeded8e98825c7c05fd9f9c8
  - name: docker.io/asonix/pictrs
    newTag: 0.5.22@sha256:4e2d90339b2b8e210b8688a3a299011895edd48bc0ba3a9476bdc320a2574b25
