---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-lemmy-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-lemmy_lemmy
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-lemmy-pictrs-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-lemmy_lemmy-pictrs
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.as212024.net
      path: k8s-k3s.fsn.as212024.net
      auth:
        kubernetes:
          mountPath: k8s-k3s.fsn.as212024.net
          role: common
          serviceAccountRef:
            name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lemmy-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: lemmy-config
            items:
              - key: config.hjson
                templateAs: Values
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-lemmy-postgres-credentials
      rewrite:
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: /services-lemmy/admin
      rewrite:
        - regexp:
            source: "(.*)"
            target: "admin_$1"
    - extract:
        key: /services-lemmy/pictrs
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pictrs_$1"
    - extract:
        key: /services-lemmy/aws-ses-lemmy
      rewrite:
        - regexp:
            source: "(.*)"
            target: "smtp_$1"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lemmy-pictrs
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-lemmy/pictrs
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pictrs-s3-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  dataFrom:
    - extract:
        key: /services-lemmy/s3-lemmy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pictrs-postgres-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        PICTRS__REPO__URL: "postgres://{{ .username }}:{{ .password }}@postgresql.fsn.as212024.net:6432/lemmy_pictrs"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-lemmy-pictrs-postgres-credentials
