---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: quay.io/curl/curl
              imagePullPolicy: IfNotPresent
              args:
                - https://cloud.lama-corp.space/cron.php
          nodeSelector:
            k8s.as212024.net/role: storage
          tolerations:
            - key: k8s.as212024.net/role
              operator: Equal
              value: storage
              effect: NoExecute
