---
kind: Kustomization

resources:
  - cronjob.yml
  - network-policy.yml
  - pvc.yml
  - secrets.yml

  - collabora

images:
  - name: quay.io/curl/curl
    newTag: 8.18.0
  - name: collabora/code
    newTag: 25.04.8.1.1
