---
netplan_configuration:
  network:
    version: 2
    ethernets:
      enp1s0: {}
      enp2s0: {}
    bonds:
      bond0:
        interfaces:
          - enp1s0
          - enp2s0
        parameters:
          mode: 802.3ad
          lacp-rate: fast
          transmit-hash-policy: layer3+4
        mtu: 9000
        addresses:
          - 172.28.2.11/27
          - 2001:67c:17fc:202::11/64
        routes:
          - to: 0.0.0.0/0
            via: 172.28.2.30
          - to: ::/0
            via: 2001:67c:17fc:202::1
