---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-lama-corp-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "lama-corp.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-lama-corp-space-https"

    - name: https-1
      hostname: "www.lama-corp.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-lama-corp-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-lama-corp-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-lama-corp-space"
  hostnames:
    - "lama-corp.space"

    - "www.lama-corp.space"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-rplace-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "rplace.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-rplace-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-rplace-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-rplace-space"
  hostnames:
    - "rplace.space"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-doyouhavegoodbackups-com"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "doyouhavegoodbackups.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-doyouhavegoodbackups-com-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-doyouhavegoodbackups-com"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-doyouhavegoodbackups-com"
  hostnames:
    - "doyouhavegoodbackups.com"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-as212024-net"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "as212024.net"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-as212024-net-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-as212024-net"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-as212024-net"
  hostnames:
    - "as212024.net"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-acdc-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "acdc.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-acdc-risson-space-https"

    - name: https-1
      hostname: "acdc.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-acdc-risson-space-https"

    - name: https-2
      hostname: "acdc.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-acdc-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-acdc-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-acdc-risson-space"
  hostnames:
    - "acdc.risson.space"

    - "acdc.marcerisson.space"

    - "acdc.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-cats-acdc-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "cats.acdc.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-cats-acdc-risson-space-https"

    - name: https-1
      hostname: "cats.acdc.epita.fr"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-cats-acdc-risson-space-https"

    - name: https-2
      hostname: "cats.acdc.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-cats-acdc-risson-space-https"

    - name: https-3
      hostname: "cats.acdc.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-cats-acdc-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-cats-acdc-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-cats-acdc-risson-space"
  hostnames:
    - "cats.acdc.risson.space"

    - "cats.acdc.epita.fr"

    - "cats.acdc.marcerisson.space"

    - "cats.acdc.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-jdmi-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "jdmi.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-jdmi-risson-space-https"

    - name: https-1
      hostname: "jdmi.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-jdmi-risson-space-https"

    - name: https-2
      hostname: "jdmi.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-jdmi-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-jdmi-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-jdmi-risson-space"
  hostnames:
    - "jdmi.risson.space"

    - "jdmi.marcerisson.space"

    - "jdmi.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

    - name: https-1
      hostname: "www.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

    - name: https-2
      hostname: "marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

    - name: https-3
      hostname: "www.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

    - name: https-4
      hostname: "risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

    - name: https-5
      hostname: "www.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-risson-space"
  hostnames:
    - "risson.space"

    - "www.risson.space"

    - "marcerisson.space"

    - "www.marcerisson.space"

    - "risson.me"

    - "www.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-scoreboard-seedbox-cri-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "scoreboard-seedbox-cri.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-scoreboard-seedbox-cri-risson-space-https"

    - name: https-1
      hostname: "scoreboard-seedbox-cri.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-scoreboard-seedbox-cri-risson-space-https"

    - name: https-2
      hostname: "scoreboard-seedbox-cri.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-scoreboard-seedbox-cri-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-scoreboard-seedbox-cri-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-scoreboard-seedbox-cri-risson-space"
  hostnames:
    - "scoreboard-seedbox-cri.risson.space"

    - "scoreboard-seedbox-cri.marcerisson.space"

    - "scoreboard-seedbox-cri.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-workshop-risson-space"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "workshop.risson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-workshop-risson-space-https"

    - name: https-1
      hostname: "workshop.marcerisson.space"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-workshop-risson-space-https"

    - name: https-2
      hostname: "workshop.risson.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-workshop-risson-space-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-workshop-risson-space"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-workshop-risson-space"
  hostnames:
    - "workshop.risson.space"

    - "workshop.marcerisson.space"

    - "workshop.risson.me"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80

---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: "static-sdlh-eu"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01-eg
    cert-manager.io/private-key-algorithm: ECDSA
    acme.cert-manager.io/http01-parentreffallback: "true"
spec:
  parentRef:
    namespace: core-eg
    name: eg-http-public
  listeners:
    - name: https
      hostname: "sdlh.eu"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: "static-sdlh-eu-https"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "static-sdlh-eu"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: "static-sdlh-eu"
  hostnames:
    - "sdlh.eu"

  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: static
          port: 80
