---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: static

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - service.yml

configMapGenerator:
  - name: static-config
    files:
      - config/nginx.conf
      - config/default.conf

images:
  - name: docker.io/library/nginx
    newTag: 1.31.4@sha256:25ee11a13a12120be02c56b9606fde6ffeeb3dff002a9e072c4a2611ab5fd995
