---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: static

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - service.yml

configMapGenerator:
  - name: static-config
    files:
      - config/nginx.conf
      - config/default.conf

images:
  - name: docker.io/library/nginx
    newTag: 1.31.2@sha256:b5a9a3cfc86b81dd6f1458d53f2ad2b559cc255653d2efd6cacee5636bf2066f
