---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: static

resources:
  - deployment.yml
  - httproute.yml
  - pvc.yml
  - service.yml

configMapGenerator:
  - name: static-config
    files:
      - config/nginx.conf
      - config/default.conf

images:
  - name: docker.io/library/nginx
    newTag: 1.31.3@sha256:640dee81b9ada2bf929ae17c2c7e88930f244216aa6418306226ce9bdc3271e6
