---
bird_router_id: 209.112.97.244

bird_static_routes:
  v4:
    - 209.112.97.0/24 unreachable
  v6:
    - 2001:67c:17fc::/48 unreachable
    - 2a06:e881:7700::/40 unreachable

bird_bgp_region_id: 276 # Germany
bird_bgp_site_id: 4

bird_bgp_preferred_source:
  v4: 209.112.97.244
  v6: 2001:67c:17fc:ffff::4

bird_bgp_originations:
  v4:
    - 209.112.97.0/24
  v6:
    - 2001:67c:17fc::/48
    - 2a06:e881:7700::/40

bird_bgp_blacklist:
  v4:
    - 194.50.92.0/24- # Local prefix
    - 5.196.188.0/25- # SBIX
    - 80.81.192.0/21- # DE-CIX
  v6:
    - 2a09:4c0:303:c232::/64- # Local prefix
    - 2001:7f8:d9:3::/64- # SBIX
    - 2001:7f8::/64- # DE-CIX

bird_bgp_sessions:
  upstreams:
    sessions:
      - description: Securebit AG
        alias: sbag
        asn: 58057
        md5: "2faf060a6c794c5fbbff6b93c64e6a94"
        multihop:
          v6: 3
        local:
          v4: 194.50.92.165
          v6: 2a09:4c0:303:c232::5ca5
        remote:
          v4: 194.50.92.250
          v6: 2a09:4c0:303:c232::5cfa
        default_med: 100
        med_metric: true
        med:
          decrease: 10

  peers:
    sessions:
      - description: DE-CIX RS1
        alias: decix_rs1
        asn: 6695
        irr: AS-DECIX AS-DECIX-V6
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.192.157
          v6: 2001:7f8::1a27:5051:c09d
        communities:
          export:
            - "0:58057"
            - "0:34549"
      - description: DE-CIX RS2
        alias: decix_rs2
        asn: 6695
        irr: AS-DECIX AS-DECIX-V6
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.193.157
          v6: 2001:7f8::1a27:5051:c19d
        communities:
          export:
            - "0:58057"
            - "0:34549"

      - description: HE Cloudflare 1
        alias: decix_cloudflare_1
        asn: 13335
        irr: AS13335:AS-CLOUDFLARE
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.194.180
          v6: 2001:7f8::3417:0:1
      - description: HE Cloudflare 2
        alias: decix_cloudflare_2
        asn: 13335
        irr: AS13335:AS-CLOUDFLARE
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.193.129
          v6: 2001:7f8::3417:0:2
      - description: HE DE-CIX
        alias: decix_he
        asn: 6939
        irr: AS-HURRICANE
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.192.172
          v6: 2001:7f8::1b1b:0:1
      - description: Meta DE-CIX 1
        alias: decix_meta_1
        asn: 32934
        irr: AS-FACEBOOK
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.194.40
          v6: 2001:7f8::80a6:0:1
      - description: Meta DE-CIX 2
        alias: decix_meta_2
        asn: 32934
        irr: AS-FACEBOOK
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.195.40
          v6: 2001:7f8::80a6:0:2
      - description: Meta DE-CIX 3
        alias: decix_meta_3
        asn: 32934
        irr: AS-FACEBOOK
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.195.141
          v6: 2001:7f8::80a6:0:3
      - description: Meta DE-CIX 4
        alias: decix_meta_4
        asn: 32934
        irr: AS-FACEBOOK
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.195.176
          v6: 2001:7f8::80a6:0:4
      - description: SIPARTECH DE-CIX
        alias: decix_sph
        asn: 8309
        irr: AS-SPH
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.195.6
          v6: 2001:7f8::2075:0:1
      - description: Google DE-CIX 1
        alias: decix_google_1
        asn: 15169
        irr: AS-GOOGLE
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.193.108
          v6: 2001:7f8::3b41:0:1
      - description: Google DE-CIX 2
        alias: decix_google_2
        asn: 15169
        irr: AS-GOOGLE
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.192.108
          v6: 2001:7f8::3b41:0:2
      - description: TKRZ DE-CIX
        alias: decix_tkrz
        asn: 42184
        irr: AS-TKRZ
        local:
          v4: 80.81.194.242
          v6: 2001:7f8::3:3c3:0:1
        remote:
          v4: 80.81.192.178
          v6: 2001:7f8::a4c8:0:1

      - description: SBIX RS1
        alias: sbix_rs1
        asn: 56755
        irr: AS-SBIX-RS
        md5: "H2j4qB78uE9cK15"
        local:
          v4: 5.196.188.52
          v6: 2001:7f8:d9:3::0003:3c38:4
        remote:
          v4: 5.196.188.1
          v6: 2001:7f8:d9:3::1
      - description: SBIX RS2
        alias: sbix_rs2
        asn: 56755
        irr: AS-SBIX-RS
        md5: "H2j4qB78uE9cK15"
        local:
          v4: 5.196.188.52
          v6: 2001:7f8:d9:3::0003:3c38:4
        remote:
          v4: 5.196.188.2
          v6: 2001:7f8:d9:3::2

  cores:
    defaults:
      local:
        v4: 209.112.97.244
        v6: 2001:67c:17fc:ffff::4
    sessions:
      - description: PVL
        alias: pvl
        asn: 212024
        remote:
          v4: 209.112.97.243
          v6: 2001:67c:17fc:ffff::3
      - description: FSN
        alias: fsn
        asn: 212024
        remote:
          v4: 209.112.97.241
          v6: 2001:67c:17fc:ffff::1
      - description: BAR
        alias: bar
        asn: 212024
        remote:
          v4: 209.112.97.242
          v6: 2001:67c:17fc:ffff::2

  looking_glasses:
    sessions:
      - description: Securebit Route Collector
        alias: securebit_rc
        asn: 44393
        multihop: 32
        local:
          v4: 209.112.97.244
          v6: 2001:67c:17fc:ffff::4
        remote:
          v4: 49.12.70.222
          v6: 2a01:4f8:c17:ec87::310c:46de

bird_ospf_sessions:
  - alias: ospf
    areas:
      0.0.0.0:
        interfaces:
          zt-lama: {}
