---
nft_define_host:
  bgp interfaces:
    name: bgp_interfaces
    value: "{core-fsn, core-bar, core-pvl}"
  bgp neighbors 4:
    name: bgp_neighbors_4
    value: "{194.50.92.250, 5.196.188.0/25, 80.81.192.0/21, 216.218.233.13}"
  bgp neighbors 6:
    name: bgp_neighbors_6
    value: "{2a09:4c0:303:c232::5cfa, 2001:7f8:d0::/64, 2001:7f8:d9:3::/64, 2001:7f8::/64, 2600:7000:1000::9}"
  ospf interfaces:
    name: ospf_interfaces
    value: "{core-fsn, core-bar, core-pvl}"

nft_input_host_rules:
  350 dns autoritative:
    - udp dport 53 accept
    - tcp dport 53 accept
  360 ntp:
    - udp dport 123 accept

nft__nat_host_postrouting_rules:
  100 external connectivity:
    - meta oif ul-sbag-0 ip saddr != {194.50.92.165, 209.112.97.0/24} snat to 194.50.92.165
