
server {
  listen       8000;
  listen       [::]:8000;
  server_name  lama-corp.space www.lama-corp.space;
  port_in_redirect  off;

  location / {
    root   /data/lama-corp.space;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  rplace.space ;
  port_in_redirect  off;

  location / {
    root   /data/rplace.space;
    index  index.html index.htm;
    autoindex on;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  doyouhavegoodbackups.com ;
  port_in_redirect  off;

  location / {
    root   /data/doyouhavegoodbackups.com;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  as212024.net ;
  port_in_redirect  off;

  location / {
    root   /data/as212024.net;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  acdc.risson.space acdc.marcerisson.space acdc.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/acdc.risson.space;
    index  index.html index.htm;
    autoindex on;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  cats.acdc.risson.space cats.acdc.epita.fr cats.acdc.marcerisson.space cats.acdc.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/cats.acdc.risson.space;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  jdmi.risson.space jdmi.marcerisson.space jdmi.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/jdmi.risson.space;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  risson.space www.risson.space marcerisson.space www.marcerisson.space risson.me www.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/risson.space;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  scoreboard-seedbox-cri.risson.space scoreboard-seedbox-cri.marcerisson.space scoreboard-seedbox-cri.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/scoreboard-seedbox-cri.risson.space;
    index  index.html index.htm;
    autoindex off;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  workshop.risson.space workshop.marcerisson.space workshop.risson.me;
  port_in_redirect  off;

  location / {
    root   /data/workshop.risson.space;
    index  index.html index.htm;
    autoindex on;
  }
}

server {
  listen       8000;
  listen       [::]:8000;
  server_name  sdlh.eu ;
  port_in_redirect  off;

  location / {
    root   /data/sdlh.eu;
    index  index.html index.htm;
    autoindex off;
  }
}
