---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ripe-atlas

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml

images:
  - name: docker.io/jamesits/ripe-atlas
    newTag: 5120@sha256:1f2a83b919bca477336afef8883df580eac1564683f73207592b4ff5e5bc568a
