---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ripe-atlas

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml

images:
  - name: jamesits/ripe-atlas
    newTag: "5120"
