---
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: ripe-atlas

resources:
  - deployment.yml
  - network-policy.yml
  - pvc.yml

images:
  - name: docker.io/jamesits/ripe-atlas
    newTag: 5130@sha256:7fb4192228030ee184b72dccf663948bafbcd08aabfc2354defc4ecd708bec50
