---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon
spec:
  template:
    spec:
      containers:
        - name: mastodon
          args:
            - exec node ./streaming/index.js
          env:
            - name: BIND
              value: "::"
          ports:
            - name: streaming
              containerPort: 4000
              protocol: TCP
