---
bird_router_id: 209.112.97.243

bird_static_routes:
  v4:
    - 209.112.97.0/24 unreachable
    - 169.254.169.254/32 via 108.61.208.1%'ul-vultr-0' # needed because multihop to vultr
  v6:
    - 2001:67c:17fc::/48 unreachable
    - 2a06:e881:7700::/40 unreachable
    - 2001:19f0:ffff::1/128 via fe80::fc00:3ff:fe21:2eeb%'ul-vultr-0' # needed because multihop to vultr

bird_bgp_region_id: 250 # France
bird_bgp_site_id: 3

bird_bgp_preferred_source:
  v4: 209.112.97.243
  v6: 2001:67c:17fc:ffff::3

bird_bgp_originations:
  v4:
    - 209.112.97.0/24
  v6:
    - 2001:67c:17fc::/48
    - 2a06:e881:7700::/40

bird_bgp_blacklist:
  v4:
    - 108.61.208.0/23 # Local prefix
  v6:
    - 2a05:f480:1c00:9ee::/64 # Local prefix
    - 2001:19f0:ffff::1/128- # Vultr router

bird_bgp_sessions:
  upstreams:
    sessions:
      - description: Vultr
        alias: vultr
        asn: 64515
        md5: "Hrf4mGfYypgK6yX8"
        multihop: 2
        local:
          v4: 108.61.208.236
          v6: 2a05:f480:1c00:9ee:5400:03ff:fe21:2eeb
        remote:
          v4: 169.254.169.254
          v6: 2001:19f0:ffff::1
        med_metric: true
        default_med: 100
        med:
          increase: 10
        # See https://github.com/vultr/vultr-docs/tree/main/faq/as20473-bgp-customer-guide
        communities:
          export:
            - 20473:6003

  peers:
    sessions:
      - description: Phowork
        alias: phowork
        asn: 212270
        irr: AS-PHOWORK
        local:
          v6: fd3c:c1c4:bbff:9a64::ee1
        remote:
          v6: fd3c:c1c4:bbff:9a64::cafe

  cores:
    defaults:
      local:
        v4: 209.112.97.243
        v6: 2001:67c:17fc:ffff::3
      med_metric: true
    sessions:
      - description: FSN
        alias: fsn
        asn: 212024
        remote:
          v4: 209.112.97.241
          v6: 2001:67c:17fc:ffff::1
      - description: BAR
        alias: bar
        asn: 212024
        remote:
          v4: 209.112.97.242
          v6: 2001:67c:17fc:ffff::2
      - description: FRA
        alias: fra
        asn: 212024
        remote:
          v4: 209.112.97.244
          v6: 2001:67c:17fc:ffff::4

  looking_glasses:
    sessions:
      - description: Securebit Route Collector
        alias: securebit_rc
        asn: 44393
        multihop: 32
        local:
          v4: 209.112.97.243
          v6: 2001:67c:17fc:ffff::3
        remote:
          v4: 49.12.70.222
          v6: 2a01:4f8:c17:ec87::310c:46de

bird_ospf_sessions:
  - alias: ospf
    areas:
      0.0.0.0:
        interfaces:
          zt-lama:
            cost: 20
          core-bar-4:
            type: ptp
            cost: 100
          core-bar-6:
            type: ptp
            cost: 100
          core-pvl-4:
            type: ptp
            cost: 100
          core-pvl-6:
            type: ptp
            cost: 100
          core-fra-4:
            type: ptp
            cost: 100
          core-fra-6:
            type: ptp
            cost: 100
