---
nft_define_host:
  bgp neighbors 4:
    name: bgp_neighbors_4
    value: "{209.112.97.240/28, 169.254.169.254/32}"
  bgp neighbors 6:
    name: bgp_neighbors_6
    value: "{2001:67c:17fc:ffff::/64, 2001:19f0:ffff::1, fd3c:c1c4:bbff:9a64::/64, 2a0c:2f07:9459::b12}"

  ospf interfaces:
    name: ospf_interfaces
    value: "{zt-lama, core-fsn-4, core-fsn-6, core-bar-4, core-bar-6, core-fra-4, core-fra-6}"

nft_input_host_rules:
  350 dns autoritative:
    - udp dport 53 accept
    - tcp dport 53 accept
  360 ntp:
    - udp dport 123 accept

  550 ppl-cri:
    - udp dport 51821 accept

nft__nat_host_postrouting_rules:
  100 external connectivity:
    - meta oif ul-vultr-0 ip saddr != {108.61.208.236, 209.112.97.0/24} snat to 108.61.208.236
