---
systemd_networkd_link:
  10-ul-vultr-0:
    Match:
      MACAddress: 56:00:03:21:2e:eb
    Link:
      Name: ul-vultr-0

systemd_networkd_netdev:
  10-id:
    NetDev:
      Name: id
      Kind: dummy
  # core VPN
  15-core-fsn:
    NetDev:
      Name: core-fsn
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51801
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/nucleus.fsn.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a01:4f8:171:b0d::1]:51803"
  15-core-bar:
    NetDev:
      Name: core-bar
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51802
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/gate-1.bar.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
  15-core-fra:
    NetDev:
      Name: core-fra
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/core/private
      ListenPort: 51804
      RouteTable: "off"
    WireGuardPeer:
      PublicKey: "{{ lookup('ansible.builtin.file', '/tmp/ansible/edge-2.fra.as212024.net/etc/wireguard/core/public') }}"
      AllowedIPs:
        - 0.0.0.0/0
        - "::/0"
      PersistentKeepalive: 60
      Endpoint: "[2a09:4c0:303:c232::5ca5]:51803"
  # private CRI peering
  30-ppl-cri-0:
    NetDev:
      Name: ppl-cri-0
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/cri/private
      ListenPort: 51821
      RouteTable: "off"
    WireGuardPeer:
      # Phowork, AS212270
      - PublicKey: E1EBL3208LQ6xt3NmxSQdkgmrPMH6bjO0tTDdASJPR8=
        AllowedIPs: fd3c:c1c4:bbff:9a64::cafe/128,2a0f:9240:2000::/48,2a0e:b107:f50::/44
        PersistentKeepalive: 60
        Endpoint: "[2001:19f0:6801:7c4:5400:3ff:fe47:7968]:51823"
  30-ppl-as201254-1:
    NetDev:
      Name: ppl-as201254-1
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/ppl-as201254/private
      ListenPort: 51822
      RouteTable: "off"
    WireGuardPeer:
      # James Landrein, AS201254
      - PublicKey: gNarVedO4h+QakoAG2b5pFXTk1nT5c9BBuC22+f+qB0=
        AllowedIPs: fd68:2402:1fbb:e377::1:20:1254/128,2a06:9801:2d::/48
        PersistentKeepalive: 60
  30-ppl-as201254-2:
    NetDev:
      Name: ppl-as201254-2
      Kind: wireguard
    WireGuard:
      PrivateKeyFile: /etc/wireguard/ppl-as201254/private
      ListenPort: 51823
      RouteTable: "off"
    WireGuardPeer:
      # James Landrein, AS201254
      - PublicKey: 2yX1Qxy+4NnFtn4vMP6US9o8xCRZa6WzH1mI9oquRHg=
        AllowedIPs: fd68:2402:1fbb:e377::2:20:1254/128,2a06:9801:2d::/48
        PersistentKeepalive: 60

systemd_networkd_network:
  10-id:
    Match:
      Name: id
    Link:
      RequiredForOnline: true
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 209.112.97.243/32
        - 2001:67c:17fc:ffff::3/128
  10-ul-vultr-0:
    Match:
      Name: ul-vultr-0
    Link:
      RequiredForOnline: true
    Network:
      LinkLocalAddressing: ipv6
      IPv6AcceptRA: true
      Address:
        - 108.61.208.236/23
        - 2a05:f480:1c00:9ee::1/64
        - 2a05:f480:1c00:9ee::53/64
        - 2a05:f480:1c00:9ee:5400:3ff:fe21:2eeb/64
    Route:
      # Default routes from Vultr
      - Destination: 0.0.0.0/0
        Gateway: 108.61.208.1
      - Destination: "::/0"
        Gateway: fe80::fc00:3ff:fe21:2eeb # transmitted in RA
      - Destination: 0.0.0.0/0
        Gateway: 108.61.208.1
        Table: 101
      - Destination: "::/0"
        Gateway: fe80::fc00:3ff:fe21:2eeb # transmitted in RA
        Table: 101
      # Needed for reaching Vultr BGP peer
      - Destination: 169.254.0.0/16
        Gateway: 108.61.208.1
        Metric: 100
      # AS212024 subnets blackholed, more specific routes exist
      - Destination: 209.112.97.0/24
        Gateway: 0.0.0.0
        Type: unreachable
      - Destination: 2001:67c:17fc::/48
        Gateway: "::"
        Type: unreachable
      - Destination: 2a06:e881:7700::/40
        Gateway: "::"
        Type: unreachable
    RoutingPolicyRule:
      # From Vultr IPs
      - From: 108.61.208.236/32
        Table: 101
      - From: 2a05:f480:1c00:9ee::/64
        Table: 101
      # core VPN
      - To: 136.243.102.29/32
        Table: 101
      - To: 2a01:4f8:171:b0d::1/128
        Table: 101
      - To: 194.50.92.165/32
        Table: 101
      - To: 2a09:4c0:303:c232::5ca5/128
        Table: 101
      # CRI interco peers
      - To: 2001:19f0:6801:7c4:5400:3ff:fe47:7968/128
        Table: 101
  # core VPN
  15-core-fsn:
    Match:
      Name: core-fsn
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.3/31
        - fe80::0:3/127
  15-core-bar:
    Match:
      Name: core-bar
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.7/31
        - fe80::0:7/127
  15-core-fra:
    Match:
      Name: core-fra
    Link:
      RequiredForOnline: false
    Network:
      LinkLocalAddressing: false
      ConfigureWithoutCarrier: true
      Address:
        - 169.254.0.10/31
        - fe80::0:10/127
  # private CRI peering
  30-ppl-cri-0:
    Match:
      Name: ppl-cri-0
    Link:
      RequiredForOnline: false
    Network:
      Address: fd3c:c1c4:bbff:9a64::ee1/64
      LinkLocalAddressing: ipv6
      ConfigureWithoutCarrier: true
  30-ppl-as201254-1:
    Match:
      Name: ppl-as201254-1
    Link:
      RequiredForOnline: false
    Network:
      Address: fd68:2402:1fbb:e377::1:21:2024/64
      LinkLocalAddressing: ipv6
      ConfigureWithoutCarrier: true
  30-ppl-as201254-2:
    Match:
      Name: ppl-as201254-2
    Link:
      RequiredForOnline: false
    Network:
      Address: fd68:2402:1fbb:e377::2:21:2024/64
      LinkLocalAddressing: ipv6
      ConfigureWithoutCarrier: true
