#!/usr/bin/env ansible-playbook
---
- name: Base
  import_playbook: base.yml

- name: Common
  import_playbook: common.yml

- name: Network
  import_playbook: network.yml

- name: DNS
  import_playbook: dns.yml

- name: KVM
  import_playbook: kvm.yml

- name: Docker
  import_playbook: docker.yml

- name: Load balancer
  import_playbook: load_balancer.yml

- name: Postgresql
  import_playbook: postgresql.yml

- name: Redis
  import_playbook: redis.yml

- name: GPS
  import_playbook: gps.yml

- name: Observability
  import_playbook: observability.yml

- name: Apps
  import_playbook: apps/main.yml

- name: Backups
  import_playbook: backups.yml
