#!/usr/bin/env ansible-playbook
---
- name: Base
  import_playbook: base.yml

- name: Unbound
  hosts: core
  roles:
    - aruhier.unbound
  tags:
    - dns
    - unbound

- name: Network
  hosts: all
  pre_tasks:
    - name: Ensure /etc/resolv.conf is up-to-date
      ansible.builtin.copy:
        content: |
          {% for ns in network_nameservers %}
          nameserver {{ ns }}
          {% endfor %}
          search .
          options edns0 trust-ad
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
      tags:
        - dns
    - name: Ensure hostname is up-to-date
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      tags:
        - dns

    - name: Ensure /etc/whois.conf is up-to-date
      ansible.builtin.copy:
        content: |
          .*  {{ whois_server }}
        dest: /etc/whois.conf
        owner: root
        group: root
        mode: 0644
      tags:
        - dns

    - name: Ensure /etc/network/interfaces is empty
      ansible.builtin.copy:
        content: ""
        dest: /etc/network/interfaces
        backup: true
        owner: root
        group: root
        mode: 0644
  roles:
    - systemd_networkd
    - mrlesmithjr.netplan
  tags:
    - netplan
    - network

- name: Firewall
  hosts: all
  pre_tasks:
    - name: Activate IP forwarding
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: true
        sysctl_set: true
        sysctl_file: /etc/sysctl.d/80-network.conf
      loop:
        - key: net.ipv4.conf.all.rp_filter
          value: 0
        - key: net.ipv4.conf.default.rp_filter
          value: 0
        - key: net.ipv4.ip_forward
          value: 1
        - key: net.ipv4.conf.all.forwarding
          value: 1
        - key: net.ipv4.conf.default.forwarding
          value: 1
        - key: net.ipv6.conf.all.forwarding
          value: 1
        - key: net.ipv6.conf.default.forwarding
          value: 1
      tags:
        - sysctl
  roles:
    - ipr-cnrs.nftables
  tags:
    - firewall
    - nftables

- name: Routers
  hosts: core
  roles:
    - role: bird
      tags:
        - bird
    - role: bird_lg_go_proxy
      tags:
        - lg
  tags:
    - router

- name: VPN
  hosts: core
  roles:
    - zerotier
  tags:
    - zerotier
    - vpn
