---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon
spec:
  template:
    spec:
      containers:
        - name: mastodon
          command:
            - bundle
            - exec
            - sidekiq
            - -c
            - "25"
            - -q
            - default,8
            - -q
            - push,6
            - -q
            - ingress,4
            - -q
            - mailers,2
            - -q
            - pull
            - -q
            - scheduler
