server:
  identity: ns0.as212024.net
  version: ""
  nsid: ns0.as212024.net
  rundir: /rundir
  listen: 0.0.0.0@5353
  listen: ::@5353

log:
  - target: stderr
    any: info

database:
  storage: /storage

include: /config/keys/*.conf

remote:
  - id: dnssec_resolver
    address: 2001:67c:17fc:ffff::1
    address: 209.112.97.241
  - id: ns1
    address: 2001:67c:17fc:ffff::3
    address: 209.112.97.243
    key: ns1_notify
  - id: ns2
    address: 2001:67c:17fc:ffff::4
    address: 209.112.97.244
    key: ns2_notify

acl:
  - id: acl_happydomain
    key: happydomain
    action: transfer
    action: update
  - id: acl_k8s_k3s-fsn-as212024-net_core-cert-manager
    key: k8s_k3s-fsn-as212024-net_core-cert-manager
    action: transfer
    action: update
  - id: acl_k8s_k3s-fsn-as212024-net_core-external-dns
    key: k8s_k3s-fsn-as212024-net_core-external-dns
    action: transfer
    action: update
  - id: ns1_xfr
    key: ns1_xfr
    address: 2001:67c:17fc:ffff::3
    address: 209.112.97.243
    action: transfer
  - id: ns2_xfr
    key: ns2_xfr
    address: 2001:67c:17fc:ffff::4
    address: 209.112.97.244
    action: transfer

submission:
  - id: dnssec_resolver
    parent: dnssec_resolver

policy:
  - id: default
    algorithm: ECDSAP256SHA256
    ksk-lifetime: 0
    zsk-lifetime: 30d
    ksk-submission: dnssec_resolver
    reproducible-signing: true
    nsec3: true
    nsec3-salt-length: 0

template:
  - id: catalog
    acl: ns1_xfr
    acl: ns2_xfr
    notify: ns1
    notify: ns2

  - id: default
    storage: /storage/zones
    file: "%s.zone"
    semantic-checks: true
    default-ttl: 300
    global-module: mod-stats
    dnssec-signing: true
    dnssec-policy: default
    acl: acl_happydomain
    acl: acl_k8s_k3s-fsn-as212024-net_core-cert-manager
    acl: acl_k8s_k3s-fsn-as212024-net_core-external-dns
    acl: ns1_xfr
    acl: ns2_xfr
    notify: ns1
    notify: ns2
    catalog-role: member
    catalog-zone: catalog.

zone:
  - domain: catalog.
    catalog-role: generate
    template: catalog

  - domain: authentik.rs
  - domain: as212024.net
  - domain: devou.ps
    dnssec-signing: false
  - domain: doyouhavegoodbackups.com
  - domain: lama-corp.space
  - domain: lama.tel
  - domain: marcerisson.space
  - domain: risson.me
  - domain: risson.net
  - domain: risson.space
  - domain: rplace.space
  - domain: thefractal.space

  - domain: 97.112.209.in-addr.arpa
  - domain: c.f.7.1.c.7.6.0.1.0.0.2.ip6.arpa
  - domain: 7.7.1.8.8.e.6.0.a.2.ip6.arpa
