---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: vault-maubot-postgres-credentials
spec:
  path: /postgres/static-creds/postgresql.fsn.as212024.net_k3s.fsn.as212024.net_services-matrix_maubot
  method: GET
  provider:
    server: https://vault.as212024.net
    auth:
      kubernetes:
        mountPath: k8s-k3s.fsn.as212024.net
        role: common
        serviceAccountRef:
          name: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maubot-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        config.yaml: |
          database: "postgresql://{{ .username }}:{{ .password }}@postgresql.fsn.as212024.net:6432/matrix_maubot"
          crypto_database: default

          plugin_directories:
            upload: /data/plugins
            load:
              - /data/plugins
            trash: /data/trash

          plugin_databases:
            sqlite: /data/dbs
            postgres: default

          server:
            hostname: "::"
            port: 29316
            public_url: https://matrix.lama-corp.space
            ui_base_path: /_matrix/maubot
            plugin_base_path: /_matrix/maubot/plugin/
            unshared_secret: "{{ .server_unshared_secret }}"
            override_resource_path: /opt/maubot/frontend

          homeservers:
            lama-corp.space:
              url: https://matrix.lama-corp.space
              secret: null

          admins:
            root: ""
            admin: "$2b$12$Go9m/HAV/5rYpCc.Ry7wb.w5CJAUvNPt0wI6LwMg6J.VtbroqBU.q"

          api_features:
            login: true
            plugin: true
            plugin_upload: true
            instance: true
            instance_database: true
            client: true
            client_proxy: true
            client_auth: true
            dev_open: true
            log: true

          logging:
            version: 1
            formatters:
              normal:
                format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
            handlers:
              console:
                class: logging.StreamHandler
                formatter: normal
            loggers:
              maubot:
                level: DEBUG
              mau:
                level: DEBUG
              aiohttp:
                level: INFO
            root:
              level: DEBUG
              handlers:
                - console
  dataFrom:
    - extract:
        key: /services-matrix/maubot/secrets
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: vault-maubot-postgres-credentials
